import Chapter02.HostKra.HostKraDualSigma
import Chapter02.HostKra.HostKraDualZ2

open Classical MeasureTheory

noncomputable section

namespace Chapter02.HostKraSevenDualFactor

universe u

open HostKraDualFunction
open HostKraDualFunctionFour
open HostKraDualTop
open HostKraDualSigma
open HostKraCubeSeminorm

/-- The data defining a bounded seven-vertex dual function. -/
structure SevenDualData
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) where
  F001 : Lp ℂ 2 M.μ
  F010 : Lp ℂ 2 M.μ
  F011 : Lp ℂ 2 M.μ
  F100 : Lp ℂ 2 M.μ
  F101 : Lp ℂ 2 M.μ
  F110 : Lp ℂ 2 M.μ
  F111 : Lp ℂ 2 M.μ
  hF001top : MemLp (fun x ↦ F001 x) ⊤ M.μ
  hF010top : MemLp (fun x ↦ F010 x) ⊤ M.μ
  hF011top : MemLp (fun x ↦ F011 x) ⊤ M.μ
  hF100top : MemLp (fun x ↦ F100 x) ⊤ M.μ
  hF101top : MemLp (fun x ↦ F101 x) ⊤ M.μ
  hF110top : MemLp (fun x ↦ F110 x) ⊤ M.μ
  hF111top : MemLp (fun x ↦ F111 x) ⊤ M.μ

/-- The `L²` dual function attached to bounded seven-vertex data. -/
def sevenDualLp
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : SevenDualData M hM) : Lp ℂ 2 M.μ :=
  sevenVertexDualFunction M hM
    q.F001 q.F010 q.F011 q.F100 q.F101 q.F110 q.F111
    q.hF001top q.hF010top q.hF011top
    q.hF100top q.hF101top q.hF110top

/-- A fixed everywhere-measurable representative of a seven-vertex dual. -/
def sevenDualRepresentative
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : SevenDualData M hM) : M.X → ℂ :=
  (Lp.memLp (sevenDualLp M hM q)).1.mk
    (fun x ↦ sevenDualLp M hM q x)

lemma sevenDualLp_ae_eq_representative
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : SevenDualData M hM) :
    (fun x ↦ sevenDualLp M hM q x) =ᵐ[M.μ]
      sevenDualRepresentative M hM q :=
  (Lp.memLp (sevenDualLp M hM q)).1.ae_eq_mk

lemma sevenDualRepresentative_measurable
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : SevenDualData M hM) :
    Measurable (sevenDualRepresentative M hM q) :=
  (Lp.memLp (sevenDualLp M hM q)).1.stronglyMeasurable_mk.measurable

/-- A measurable representative and one of its forward Koopman shifts. -/
def sevenDualOrbitRepresentative
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (nq : ℕ × SevenDualData M hM) : M.X → ℂ :=
  sevenDualRepresentative M hM nq.2 ∘ (M.T^[nq.1])

/-- The family of all forward shifts of measurable representatives of
bounded seven-vertex dual functions. -/
def sevenDualRepresentatives
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) :
    Set (M.X → ℂ) :=
  Set.range (sevenDualOrbitRepresentative M hM)

/-- The factor generated by all bounded seven-vertex dual functions. -/
def sevenDualMeasurableSpace
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) :
    MeasurableSpace M.X :=
  generatedByFunctions (sevenDualRepresentatives M hM)

theorem sevenDualMeasurableSpace_le
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) :
    sevenDualMeasurableSpace M hM ≤ M.measurableSpace := by
  apply generatedByFunctions_le
  intro d hd
  obtain ⟨⟨n, q⟩, rfl⟩ := hd
  exact (sevenDualRepresentative_measurable M hM q).comp
    (hM.2.measurable.iterate n)

/-- The system transformation is measurable on the sigma-algebra generated
by all forward shifts of seven-vertex duals. -/
theorem sevenDualMeasurableSpace_transform_measurable
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) :
    @Measurable M.X M.X
      (sevenDualMeasurableSpace M hM)
      (sevenDualMeasurableSpace M hM) M.T := by
  rw [measurable_iff_comap_le]
  unfold sevenDualMeasurableSpace generatedByFunctions
  rw [MeasurableSpace.comap_iSup]
  apply iSup_le
  intro d
  have hcomp :
      MeasurableSpace.comap M.T
          (MeasurableSpace.comap d.1 (borel ℂ)) =
        MeasurableSpace.comap (d.1 ∘ M.T) (borel ℂ) := by
    ext s
    simp
  rw [hcomp]
  change MeasurableSpace.comap (d.1 ∘ M.T) (borel ℂ) ≤
    ⨆ e : sevenDualRepresentatives M hM,
      MeasurableSpace.comap e.1 (borel ℂ)
  obtain ⟨⟨n, q⟩, hd⟩ := d.2
  have hshift :
      d.1 ∘ M.T =
        sevenDualOrbitRepresentative M hM (n + 1, q) := by
    rw [← hd]
    funext x
    simp only [sevenDualOrbitRepresentative, Function.comp_apply]
    rw [Function.iterate_succ_apply]
  rw [hshift]
  exact le_iSup_of_le
    (⟨sevenDualOrbitRepresentative M hM (n + 1, q),
      ⟨(n + 1, q), rfl⟩⟩ : sevenDualRepresentatives M hM) le_rfl

theorem sevenDualRepresentative_measurable_factor
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : SevenDualData M hM) :
    @Measurable M.X ℂ (sevenDualMeasurableSpace M hM) (borel ℂ)
      (sevenDualRepresentative M hM q) := by
  have hzero :
      sevenDualOrbitRepresentative M hM (0, q) =
        sevenDualRepresentative M hM q := by
    rfl
  rw [← hzero]
  exact measurable_generatedByFunctions
    (sevenDualRepresentatives M hM) ⟨(0, q), rfl⟩

lemma sevenDualLp_aestronglyMeasurable_factor
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : SevenDualData M hM) :
    @AEStronglyMeasurable M.X ℂ _
      (sevenDualMeasurableSpace M hM) M.measurableSpace
      (fun x ↦ sevenDualLp M hM q x) M.μ := by
  have hrep :
      @AEStronglyMeasurable M.X ℂ _
        (sevenDualMeasurableSpace M hM) M.measurableSpace
        (sevenDualRepresentative M hM q) M.μ :=
    (sevenDualRepresentative_measurable_factor M hM q).aestronglyMeasurable
  exact hrep.congr (sevenDualLp_ae_eq_representative M hM q).symm

/-- The `L²` residual after projection to the seven-dual factor. -/
def sevenDualResidual
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (F : Lp ℂ 2 M.μ) : Lp ℂ 2 M.μ :=
  F - condExpL2Value M.μ (sevenDualMeasurableSpace_le M hM) F

lemma sevenDualResidual_memLp_top
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (F : Lp ℂ 2 M.μ)
    (hFtop : MemLp (fun x ↦ F x) ⊤ M.μ) :
    MemLp (fun x ↦ sevenDualResidual M hM F x) ⊤ M.μ := by
  letI : IsProbabilityMeasure M.μ := hM.1
  exact sub_condExpL2Value_memLp_top M.μ
    (sevenDualMeasurableSpace_le M hM) F hFtop

/-- A bounded vector minus its conditional projection to the factor
generated by seven-vertex duals has zero Host--Kra `U³` seminorm. -/
theorem sub_sevenDualProjection_hasZeroHostKraU3
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (F : Lp ℂ 2 M.μ)
    (hFtop : MemLp (fun x ↦ F x) ⊤ M.μ) :
    HasZeroHostKraU3 M hM
      (fun x ↦ sevenDualResidual M hM F x)
      (sevenDualResidual_memLp_top M hM F hFtop) := by
  letI : IsProbabilityMeasure M.μ := hM.1
  let m := sevenDualMeasurableSpace M hM
  let hm : m ≤ M.measurableSpace := sevenDualMeasurableSpace_le M hM
  let R := sevenDualResidual M hM F
  let hRtop := sevenDualResidual_memLp_top M hM F hFtop
  let G := ForwardKroneckerFactor.lpStar M R
  let hGtop := lpStar_memLp_top M R hRtop
  let Gs := ForwardKroneckerFactor.lpStar M G
  let hGstop := lpStar_memLp_top M G hGtop
  let q : SevenDualData M hM := {
    F001 := Gs
    F010 := Gs
    F011 := G
    F100 := Gs
    F101 := G
    F110 := G
    F111 := Gs
    hF001top := hGstop
    hF010top := hGstop
    hF011top := hGtop
    hF100top := hGstop
    hF101top := hGtop
    hF110top := hGtop
    hF111top := hGstop
  }
  have hpairR :
      @inner ℂ (Lp ℂ 2 M.μ) _ R (sevenDualLp M hM q) = 0 := by
    exact inner_sub_condExpL2Value_eq_zero M.μ hm F
      (sevenDualLp M hM q)
      (sevenDualLp_aestronglyMeasurable_factor M hM q)
  have hGsR : Gs = R := by
    exact HostKraDualFunctionFour.lpStar_lpStar M R
  have hpairG :
      let Gs' := ForwardKroneckerFactor.lpStar M G
      let hGstop' := lpStar_memLp_top M G hGtop
      @inner ℂ (Lp ℂ 2 M.μ) _ Gs'
        (sevenVertexDualFunction M hM
          Gs' Gs' G Gs' G G Gs'
          hGstop' hGstop' hGtop hGstop' hGtop hGtop) = 0 := by
    dsimp only
    simpa only [q, sevenDualLp, Gs, hGsR] using hpairR
  have hGzero :
      HasZeroHostKraU3 M hM (fun x ↦ G x) hGtop :=
    (Chapter02.HostKraDualZ2.hasZeroHostKraU3_iff_inner_lpStar_parityDual_eq_zero
      M hM G hGtop).2 hpairG
  have hstarZero :=
    Chapter02.HostKraU3Nullspace.hasZeroHostKraU3_star
      M hM (fun x ↦ G x) hGtop hGzero
  have hstarAe :
      (fun x ↦ star (G x)) =ᵐ[M.μ] fun x ↦ R x := by
    have h := ForwardKroneckerFactor.lpStar_coe M G
    rw [show ForwardKroneckerFactor.lpStar M G = R by
      exact HostKraDualFunctionFour.lpStar_lpStar M R] at h
    exact h.symm
  exact Chapter02.HostKraU3Nullspace.hasZeroHostKraU3_congr
    M hM (fun x ↦ star (G x)) (fun x ↦ R x)
    hGtop.star hRtop hstarAe hstarZero

end Chapter02.HostKraSevenDualFactor
