import Chapter02.Dynamics.CompactCodingDensity
import Chapter02.HostKra.HostKraFiniteCoordinate
import Mathlib.Analysis.SpecialFunctions.Sigmoid

open Classical MeasureTheory Set

noncomputable section

namespace Chapter02.HostKraFiniteCylinderDensity

universe u

/-- A compact, injective coding of one complex coordinate.  The real and
imaginary parts are sent into the compact unit interval by the sigmoid
embedding. -/
def compactComplexCode (z : ℂ) : unitInterval × unitInterval :=
  (unitInterval.sigmoid z.re, unitInterval.sigmoid z.im)

lemma compactComplexCode_continuous : Continuous compactComplexCode := by
  exact
    (unitInterval.continuous_sigmoid.comp Complex.continuous_re).prodMk
      (unitInterval.continuous_sigmoid.comp Complex.continuous_im)

lemma compactComplexCode_injective :
    Function.Injective compactComplexCode := by
  intro z w hzw
  apply Complex.ext
  · exact unitInterval.sigmoid_injective (congrArg Prod.fst hzw)
  · exact unitInterval.sigmoid_injective (congrArg Prod.snd hzw)

lemma compactComplexCode_measurableEmbedding :
    MeasurableEmbedding compactComplexCode :=
  compactComplexCode_continuous.measurableEmbedding
    compactComplexCode_injective

/-- The compact finite-coordinate coding space associated with a set of
canonical fifteen-dual coordinates. -/
abbrev FiniteCodeSpace
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (t : Set
      (HostKraFifteenDualFactor.parityFifteenDualRepresentatives M hM)) :=
  t → (unitInterval × unitInterval)

/-- Simultaneously code the specified fifteen-dual coordinates into a
finite product of compact intervals. -/
def finiteCode
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (t : Set
      (HostKraFifteenDualFactor.parityFifteenDualRepresentatives M hM)) :
    M.X → FiniteCodeSpace M hM t :=
  fun x d ↦ compactComplexCode (d.1.1 x)

lemma coordinate_measurable
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (d :
      HostKraFifteenDualFactor.parityFifteenDualRepresentatives M hM) :
    Measurable d.1 := by
  obtain ⟨⟨n, q⟩, hd⟩ := d.2
  rw [← hd]
  exact
    (HostKraFifteenDualFactor.parityFifteenDualRepresentative_measurable
      M hM q).comp (hM.2.measurable.iterate n)

lemma finiteCode_measurable
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (t : Set
      (HostKraFifteenDualFactor.parityFifteenDualRepresentatives M hM)) :
    Measurable (finiteCode M hM t) := by
  rw [measurable_pi_iff]
  intro d
  exact compactComplexCode_measurableEmbedding.measurable.comp
    (coordinate_measurable M hM d.1)

lemma compactComplexCode_comap :
    MeasurableSpace.comap compactComplexCode
        (inferInstance : MeasurableSpace
          (unitInterval × unitInterval)) =
      (inferInstance : MeasurableSpace ℂ) :=
  compactComplexCode_measurableEmbedding.comap_eq

/-- The sigma-algebra generated by a finite family of complex
fifteen-dual coordinates is exactly the pullback of the Borel sigma-algebra
of their compact simultaneous code. -/
theorem finiteFifteenDualMeasurableSpace_eq_comap
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (t : Set
      (HostKraFifteenDualFactor.parityFifteenDualRepresentatives M hM))
    (ht : t.Finite) :
    HostKraFiniteCoordinate.finiteFifteenDualMeasurableSpace M hM t =
      MeasurableSpace.comap (finiteCode M hM t)
        (borel (FiniteCodeSpace M hM t)) := by
  letI : Fintype t := ht.fintype
  rw [← BorelSpace.measurable_eq]
  unfold HostKraFiniteCoordinate.finiteFifteenDualMeasurableSpace
    HostKraFiniteCoordinate.coordinateSup
  change
    (⨆ d, ⨆ (_hd : d ∈ t),
        MeasurableSpace.comap d.1 (borel ℂ)) =
      MeasurableSpace.comap (finiteCode M hM t)
        MeasurableSpace.pi
  rw [show
      (MeasurableSpace.pi :
        MeasurableSpace (FiniteCodeSpace M hM t)) =
        ⨆ i, MeasurableSpace.comap (fun z ↦ z i)
          (inferInstance : MeasurableSpace
            (unitInterval × unitInterval)) by
      rfl]
  rw [MeasurableSpace.comap_iSup]
  simp_rw [MeasurableSpace.comap_comp]
  apply le_antisymm
  · refine iSup_le fun d ↦ iSup_le fun hd ↦ ?_
    refine le_iSup_of_le (⟨d, hd⟩ : t) ?_
    have hcoord :
        MeasurableSpace.comap
            (fun x ↦ compactComplexCode (d.1 x))
            (inferInstance : MeasurableSpace
              (unitInterval × unitInterval)) =
          MeasurableSpace.comap d.1
            (inferInstance : MeasurableSpace ℂ) := by
      rw [show (fun x ↦ compactComplexCode (d.1 x)) =
          compactComplexCode ∘ d.1 by rfl,
        ← MeasurableSpace.comap_comp, compactComplexCode_comap]
    simpa only [BorelSpace.measurable_eq, finiteCode,
      Function.comp_apply] using hcoord.symm.le
  · refine iSup_le fun d ↦ ?_
    refine le_iSup_of_le d.1 (le_iSup_of_le d.2 ?_)
    have hcoord :
        MeasurableSpace.comap
            (fun x ↦ compactComplexCode (d.1.1 x))
            (inferInstance : MeasurableSpace
              (unitInterval × unitInterval)) =
          MeasurableSpace.comap d.1.1
            (inferInstance : MeasurableSpace ℂ) := by
      rw [show (fun x ↦ compactComplexCode (d.1.1 x)) =
          compactComplexCode ∘ d.1.1 by rfl,
        ← MeasurableSpace.comap_comp, compactComplexCode_comap]
    simpa only [BorelSpace.measurable_eq, finiteCode,
      Function.comp_apply] using hcoord.le

/-- Every `L²` vector measurable with respect to finitely many canonical
fifteen-dual coordinates can be approximated by a continuous function of
their compact simultaneous code. -/
theorem exists_continuous_finiteCode_norm_sub_lt
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (t : Set
      (HostKraFifteenDualFactor.parityFifteenDualRepresentatives M hM))
    (ht : t.Finite)
    (Q : Lp ℂ 2 M.μ)
    (hQ : Q ∈ MeasureTheory.lpMeas ℂ ℂ
      (HostKraFiniteCoordinate.finiteFifteenDualMeasurableSpace M hM t)
      2 M.μ)
    {η : ℝ} (hη : 0 < η) :
    letI : IsProbabilityMeasure M.μ := hM.1
    letI := ht.fintype
    letI : IsFiniteMeasure
        (Measure.map (finiteCode M hM t) M.μ) :=
      Measure.isFiniteMeasure_map M.μ (finiteCode M hM t)
    ∃ φ : C(FiniteCodeSpace M hM t, ℂ),
      ‖Q -
          MeasureTheory.Lp.compMeasurePreservingₗᵢ ℂ
            (finiteCode M hM t)
            ⟨finiteCode_measurable M hM t, rfl⟩
            (ContinuousMap.toLp 2
              (Measure.map (finiteCode M hM t) M.μ) ℂ φ)‖ < η := by
  letI : IsProbabilityMeasure M.μ := hM.1
  letI : Fintype t := ht.fintype
  letI : IsFiniteMeasure
      (Measure.map (finiteCode M hM t) M.μ) :=
    Measure.isFiniteMeasure_map M.μ (finiteCode M hM t)
  apply
    CompactCodingDensity.exists_continuous_comp_norm_sub_lt
      M.μ (finiteCode M hM t) (finiteCode_measurable M hM t) Q
  have hsigma :=
    finiteFifteenDualMeasurableSpace_eq_comap M hM t ht
  rw [← BorelSpace.measurable_eq] at hsigma
  rw [← hsigma]
  exact hQ
  exact hη

end Chapter02.HostKraFiniteCylinderDensity
