import Chapter02.HostKra.HostKraDualTop

open Classical MeasureTheory

noncomputable section

namespace Chapter02.HostKraDualSigma

universe u

/-- The smallest measurable space generated by a family of complex-valued
functions, expressed as the supremum of their pullback Borel spaces. -/
def generatedByFunctions
    {X : Type u} (𝒟 : Set (X → ℂ)) : MeasurableSpace X :=
  ⨆ d : 𝒟, MeasurableSpace.comap d.1 (borel ℂ)

theorem generatedByFunctions_le
    {X : Type u} [m₀ : MeasurableSpace X]
    (𝒟 : Set (X → ℂ))
    (h𝒟 : ∀ d ∈ 𝒟, Measurable d) :
    generatedByFunctions 𝒟 ≤ m₀ := by
  apply iSup_le
  intro d
  exact measurable_iff_comap_le.mp (h𝒟 d.1 d.2)

theorem measurable_generatedByFunctions
    {X : Type u} (𝒟 : Set (X → ℂ))
    {d : X → ℂ} (hd : d ∈ 𝒟) :
    @Measurable X ℂ (generatedByFunctions 𝒟) (borel ℂ) d := by
  rw [measurable_iff_comap_le]
  exact le_iSup_of_le (⟨d, hd⟩ : 𝒟) le_rfl

/-- The `L²` conditional projection, viewed in the ambient `L²` space. -/
def condExpL2Value
    {X : Type u} {m m₀ : MeasurableSpace X}
    (μ : Measure X) (hm : m ≤ m₀) (F : Lp ℂ 2 μ) :
    Lp ℂ 2 μ :=
  ((condExpL2 ℂ ℂ hm) F).1

/-- The `L²` conditional projection of an essentially bounded vector is
again essentially bounded. -/
theorem condExpL2Value_memLp_top
    {X : Type u} {m m₀ : MeasurableSpace X}
    (μ : Measure X) [IsFiniteMeasure μ]
    (hm : m ≤ m₀) [SigmaFinite (μ.trim hm)]
    (F : Lp ℂ 2 μ)
    (hFtop : MemLp (fun x ↦ F x) ⊤ μ) :
    MemLp (fun x ↦ condExpL2Value μ hm F x) ⊤ μ := by
  have hFint : Integrable (fun x ↦ F x) μ :=
    (Lp.memLp F).integrable (by norm_num)
  have hce :
      (fun x ↦ condExpL2Value μ hm F x) =ᵐ[μ]
        condExp m μ (fun x ↦ F x) := by
    have hce' :=
      (Lp.memLp F).condExpL2_ae_eq_condExp'
        (𝕜 := ℂ) hm hFint
    rw [Lp.toLp_coeFn] at hce'
    simpa only [condExpL2Value] using hce'
  exact (memLp_congr_ae hce).mpr
    (Chapter02.HostKraConditionalTop.condExp_memLp_top
      μ hm (fun x ↦ F x) hFtop)

/-- Subtracting the factor projection from a bounded vector leaves a
bounded residual. -/
theorem sub_condExpL2Value_memLp_top
    {X : Type u} {m m₀ : MeasurableSpace X}
    (μ : Measure X) [IsFiniteMeasure μ]
    (hm : m ≤ m₀) [SigmaFinite (μ.trim hm)]
    (F : Lp ℂ 2 μ)
    (hFtop : MemLp (fun x ↦ F x) ⊤ μ) :
    MemLp
      (fun x ↦ (F - condExpL2Value μ hm F) x)
      ⊤ μ := by
  have hsub := hFtop.sub (condExpL2Value_memLp_top μ hm F hFtop)
  exact (memLp_congr_ae
    (Lp.coeFn_sub F (condExpL2Value μ hm F))).mpr hsub

/-- The residual from conditional projection is orthogonal to every
`L²` vector measurable with respect to the generated factor. -/
theorem inner_sub_condExpL2Value_eq_zero
    {X : Type u} {m m₀ : MeasurableSpace X}
    (μ : Measure X) (hm : m ≤ m₀)
    (F D : Lp ℂ 2 μ)
    (hD : @AEStronglyMeasurable X ℂ _ m m₀
      (fun x ↦ D x) μ) :
    @inner ℂ (Lp ℂ 2 μ) _
      (F - condExpL2Value μ hm F) D = 0 := by
  have hinner :=
    inner_condExpL2_eq_inner_fun (𝕜 := ℂ) hm F D hD
  have hinner' :
      @inner ℂ (Lp ℂ 2 μ) _ (condExpL2Value μ hm F) D =
        @inner ℂ (Lp ℂ 2 μ) _ F D := by
    simpa only [condExpL2Value] using hinner
  rw [inner_sub_left, hinner', sub_self]

end Chapter02.HostKraDualSigma
