import Chapter02.HostKra.HostKraDualSigma
import Chapter02.HostKra.HostKraDualZ3

open Classical MeasureTheory

noncomputable section

namespace Chapter02.HostKraFifteenDualFactor

universe u

open HostKraDualFunction
open HostKraDualFunctionFour
open HostKraDualTop
open HostKraDualSigma
open HostKraCubeSeminorm

/-- A bounded `L²` vector, used to index the canonical parity
fifteen-vertex duals. -/
structure BoundedLpData
    (M : System.{u}) where
  F : Lp ℂ 2 M.μ
  hFtop : MemLp (fun x ↦ F x) ⊤ M.μ

/-- The canonical parity fifteen-vertex dual attached to a bounded vector. -/
def parityFifteenDualLp
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : BoundedLpData M) : Lp ℂ 2 M.μ :=
  let Fs := ForwardKroneckerFactor.lpStar M q.F
  let hFstop := lpStar_memLp_top M q.F q.hFtop
  fifteenVertexDualFunction M hM
    Fs Fs q.F Fs q.F q.F Fs
    Fs q.F q.F Fs q.F Fs Fs q.F
    hFstop hFstop q.hFtop hFstop q.hFtop q.hFtop hFstop
    hFstop q.hFtop q.hFtop hFstop q.hFtop hFstop hFstop

lemma parityFifteenDualLp_memLp_top
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : BoundedLpData M) :
    MemLp (fun x ↦ parityFifteenDualLp M hM q x) ⊤ M.μ := by
  dsimp only [parityFifteenDualLp]
  exact fifteenVertexDualFunction_memLp_top M hM
    (ForwardKroneckerFactor.lpStar M q.F)
    (ForwardKroneckerFactor.lpStar M q.F) q.F
    (ForwardKroneckerFactor.lpStar M q.F) q.F q.F
    (ForwardKroneckerFactor.lpStar M q.F)
    (ForwardKroneckerFactor.lpStar M q.F) q.F q.F
    (ForwardKroneckerFactor.lpStar M q.F) q.F
    (ForwardKroneckerFactor.lpStar M q.F)
    (ForwardKroneckerFactor.lpStar M q.F) q.F
    (lpStar_memLp_top M q.F q.hFtop)
    (lpStar_memLp_top M q.F q.hFtop) q.hFtop
    (lpStar_memLp_top M q.F q.hFtop) q.hFtop q.hFtop
    (lpStar_memLp_top M q.F q.hFtop)
    (lpStar_memLp_top M q.F q.hFtop) q.hFtop q.hFtop
    (lpStar_memLp_top M q.F q.hFtop) q.hFtop
    (lpStar_memLp_top M q.F q.hFtop)
    (lpStar_memLp_top M q.F q.hFtop) q.hFtop

/-- An everywhere-measurable representative of a canonical parity dual. -/
def parityFifteenDualRepresentative
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : BoundedLpData M) : M.X → ℂ :=
  (Lp.memLp (parityFifteenDualLp M hM q)).1.mk
    (fun x ↦ parityFifteenDualLp M hM q x)

lemma parityFifteenDualLp_ae_eq_representative
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : BoundedLpData M) :
    (fun x ↦ parityFifteenDualLp M hM q x) =ᵐ[M.μ]
      parityFifteenDualRepresentative M hM q :=
  (Lp.memLp (parityFifteenDualLp M hM q)).1.ae_eq_mk

lemma parityFifteenDualRepresentative_measurable
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : BoundedLpData M) :
    Measurable (parityFifteenDualRepresentative M hM q) :=
  (Lp.memLp (parityFifteenDualLp M hM q)).1
    |>.stronglyMeasurable_mk.measurable

/-- A canonical parity dual representative and one of its forward shifts. -/
def parityFifteenDualOrbitRepresentative
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (nq : ℕ × BoundedLpData M) : M.X → ℂ :=
  parityFifteenDualRepresentative M hM nq.2 ∘ (M.T^[nq.1])

def parityFifteenDualRepresentatives
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) :
    Set (M.X → ℂ) :=
  Set.range (parityFifteenDualOrbitRepresentative M hM)

/-- The factor generated by the canonical parity fifteen-vertex duals. -/
def fifteenDualMeasurableSpace
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) :
    MeasurableSpace M.X :=
  generatedByFunctions (parityFifteenDualRepresentatives M hM)

theorem fifteenDualMeasurableSpace_le
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) :
    fifteenDualMeasurableSpace M hM ≤ M.measurableSpace := by
  apply generatedByFunctions_le
  intro d hd
  obtain ⟨⟨n, q⟩, rfl⟩ := hd
  exact (parityFifteenDualRepresentative_measurable M hM q).comp
    (hM.2.measurable.iterate n)

/-- The system transformation is measurable on the sigma-algebra generated
by all forward shifts of canonical parity fifteen-vertex duals. -/
theorem fifteenDualMeasurableSpace_transform_measurable
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M) :
    @Measurable M.X M.X
      (fifteenDualMeasurableSpace M hM)
      (fifteenDualMeasurableSpace M hM) M.T := by
  rw [measurable_iff_comap_le]
  unfold fifteenDualMeasurableSpace generatedByFunctions
  rw [MeasurableSpace.comap_iSup]
  apply iSup_le
  intro d
  have hcomp :
      MeasurableSpace.comap M.T
          (MeasurableSpace.comap d.1 (borel ℂ)) =
        MeasurableSpace.comap (d.1 ∘ M.T) (borel ℂ) := by
    ext s
    simp
  rw [hcomp]
  change MeasurableSpace.comap (d.1 ∘ M.T) (borel ℂ) ≤
    ⨆ e : parityFifteenDualRepresentatives M hM,
      MeasurableSpace.comap e.1 (borel ℂ)
  obtain ⟨⟨n, q⟩, hd⟩ := d.2
  have hshift :
      d.1 ∘ M.T =
        parityFifteenDualOrbitRepresentative M hM (n + 1, q) := by
    rw [← hd]
    funext x
    simp only [parityFifteenDualOrbitRepresentative, Function.comp_apply]
    rw [Function.iterate_succ_apply]
  rw [hshift]
  exact le_iSup_of_le
    (⟨parityFifteenDualOrbitRepresentative M hM (n + 1, q),
      ⟨(n + 1, q), rfl⟩⟩ : parityFifteenDualRepresentatives M hM) le_rfl

lemma parityFifteenDualLp_aestronglyMeasurable_factor
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (q : BoundedLpData M) :
    @AEStronglyMeasurable M.X ℂ _
      (fifteenDualMeasurableSpace M hM) M.measurableSpace
      (fun x ↦ parityFifteenDualLp M hM q x) M.μ := by
  have hrepMeas :
      @Measurable M.X ℂ (fifteenDualMeasurableSpace M hM) (borel ℂ)
        (parityFifteenDualRepresentative M hM q) :=
    by
      have hzero :
          parityFifteenDualOrbitRepresentative M hM (0, q) =
            parityFifteenDualRepresentative M hM q := by
        rfl
      rw [← hzero]
      exact measurable_generatedByFunctions
        (parityFifteenDualRepresentatives M hM) ⟨(0, q), rfl⟩
  have hrep :
      @AEStronglyMeasurable M.X ℂ _
        (fifteenDualMeasurableSpace M hM) M.measurableSpace
        (parityFifteenDualRepresentative M hM q) M.μ :=
    hrepMeas.aestronglyMeasurable
  exact hrep.congr
    (parityFifteenDualLp_ae_eq_representative M hM q).symm

def fifteenDualResidual
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (F : Lp ℂ 2 M.μ) : Lp ℂ 2 M.μ :=
  F - condExpL2Value M.μ (fifteenDualMeasurableSpace_le M hM) F

lemma fifteenDualResidual_memLp_top
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (F : Lp ℂ 2 M.μ)
    (hFtop : MemLp (fun x ↦ F x) ⊤ M.μ) :
    MemLp (fun x ↦ fifteenDualResidual M hM F x) ⊤ M.μ := by
  letI : IsProbabilityMeasure M.μ := hM.1
  exact sub_condExpL2Value_memLp_top M.μ
    (fifteenDualMeasurableSpace_le M hM) F hFtop

/-- A bounded vector minus its conditional projection to the factor
generated by parity fifteen-vertex duals has zero Host--Kra `U⁴`
seminorm. -/
theorem sub_fifteenDualProjection_hasZeroHostKraU4
    (M : System.{u}) [StandardBorelSpace M.X]
    (hM : Chapter01.IsMeasurePreservingSystem M)
    (F : Lp ℂ 2 M.μ)
    (hFtop : MemLp (fun x ↦ F x) ⊤ M.μ) :
    HasZeroHostKraU4 M hM
      (fun x ↦ fifteenDualResidual M hM F x)
      (fifteenDualResidual_memLp_top M hM F hFtop) := by
  letI : IsProbabilityMeasure M.μ := hM.1
  let m := fifteenDualMeasurableSpace M hM
  let hm : m ≤ M.measurableSpace := fifteenDualMeasurableSpace_le M hM
  let R := fifteenDualResidual M hM F
  let hRtop := fifteenDualResidual_memLp_top M hM F hFtop
  let G := ForwardKroneckerFactor.lpStar M R
  let hGtop := lpStar_memLp_top M R hRtop
  let q : BoundedLpData M := { F := G, hFtop := hGtop }
  have hpairR :
      @inner ℂ (Lp ℂ 2 M.μ) _ R
        (parityFifteenDualLp M hM q) = 0 := by
    exact inner_sub_condExpL2Value_eq_zero M.μ hm F
      (parityFifteenDualLp M hM q)
      (parityFifteenDualLp_aestronglyMeasurable_factor M hM q)
  have hpairG :
      let Gs := ForwardKroneckerFactor.lpStar M G
      let hGstop := lpStar_memLp_top M G hGtop
      @inner ℂ (Lp ℂ 2 M.μ) _ Gs
        (fifteenVertexDualFunction M hM
          Gs Gs G Gs G G Gs
          Gs G G Gs G Gs Gs G
          hGstop hGstop hGtop hGstop hGtop hGtop hGstop
          hGstop hGtop hGtop hGstop hGtop hGstop hGstop) = 0 := by
    dsimp only
    have hGsR :
        ForwardKroneckerFactor.lpStar M G = R :=
      HostKraDualFunctionFour.lpStar_lpStar M R
    simpa only [q, parityFifteenDualLp, hGsR] using hpairR
  have hGzero :
      HasZeroHostKraU4 M hM (fun x ↦ G x) hGtop :=
    (Chapter02.HostKraDualZ3.hasZeroHostKraU4_iff_inner_lpStar_parityDual_eq_zero
      M hM G hGtop).2 hpairG
  have hstarZero :=
    Chapter02.HostKraU4Nullspace.hasZeroHostKraU4_star
      M hM (fun x ↦ G x) hGtop hGzero
  have hstarAe :
      (fun x ↦ star (G x)) =ᵐ[M.μ] fun x ↦ R x := by
    have h := ForwardKroneckerFactor.lpStar_coe M G
    rw [show ForwardKroneckerFactor.lpStar M G = R by
      exact HostKraDualFunctionFour.lpStar_lpStar M R] at h
    exact h.symm
  exact Chapter02.HostKraU4Nullspace.hasZeroHostKraU4_congr
    M hM (fun x ↦ star (G x)) (fun x ↦ R x)
    hGtop.star hRtop hstarAe hstarZero

end Chapter02.HostKraFifteenDualFactor
