import Chapter00.Common

#check csSup_le
#check le_csSup
#check le_csInf
#check csInf_le
#check csSup_le_iff
#check le_csInf_iff
#check bddAbove_def
#check bddBelow_def
#check Finset.card_filter_le_iff
#check Finset.card_filter_le
#check Finset.filter_union
#check Finset.filter_compl
#check Set.ncard_union_le
#check Set.Finite.card_union_le
#check tendsto_natCast_atTop_atTop
#check Filter.Eventually
#check Filter.liminf
#check Filter.limsup
#check Filter.liminf_eq
#check Filter.limsup_eq
#check Filter.liminf_le_limsup
#check Filter.limsup_add_le
#check Filter.liminf_add_le
#check Filter.liminf_add_limsup_le_liminf_add
#check Filter.limsup_neg
#check Filter.liminf_neg
#check Filter.limsup_le_limsup
#check Filter.liminf_le_liminf
#check Filter.limsup_le_limsup_of_le
#check Filter.liminf_le_liminf_of_le
#check Filter.limsup_le
#check le_liminf
#check Filter.limsup_const
#check Filter.liminf_const
#check Filter.limsup_add
#check Filter.liminf_add
#check Filter.NeBot.comap
#check Filter.comap_neBot_iff
#check Filter.eventually_comap
#check Filter.Eventually.filter_mono
#check limsup_add_le
#check le_liminf_add
#check Filter.limsup_const_sub
#check Filter.liminf_const_sub
#check Finset.filter_card_add_filter_neg_card_eq_card
#check Finset.card_filter_add_card_filter_neg_eq
#check Finset.card_union_of_disjoint
#check Finset.disjoint_filter_filter_neg
#check div_le_one
#check div_add_div_same
#check sub_div
#check Filter.tendsto_comap_iff
#check Filter.tendsto_comap
#check Filter.Tendsto.limsup_comp_le_limsup
#check Filter.Tendsto.liminf_le_liminf_comp
#check Finset.filter_congr_decidable
#check Finset.filter_congr
