import Chapter02.Spectral.SpectralRelations

open Classical Filter Set

noncomputable section

namespace Chapter02.SpectralDecomposition

universe u

/-- The minimal closed reducing subspace generated by a vector, packaged as a
linear subspace.  This is the concrete Hilbert-space object underlying
`InCyclicSubspace`. -/
def cyclicSubmodule (D : HilbertOperatorData.{u}) (x : D.H) : Submodule ℂ D.H where
  carrier := {y | InCyclicSubspace D x y}
  zero_mem' := by
    intro K hK hx
    exact hK.1
  add_mem' := by
    intro y z hy hz K hK hx
    simpa using hK.2.1 y (hy K hK hx) z (hz K hK hx) 1 1
  smul_mem' := by
    intro c y hy K hK hx
    simpa using hK.2.1 y (hy K hK hx) 0 hK.1 c 0

@[simp] theorem mem_cyclicSubmodule_iff (D : HilbertOperatorData.{u})
    (x y : D.H) : y ∈ cyclicSubmodule D x ↔ InCyclicSubspace D x y := Iff.rfl

theorem cyclicSubmodule_reducing (D : HilbertOperatorData.{u}) (x : D.H) :
    IsClosedReducingSubspace D (cyclicSubmodule D x : Set D.H) := by
  refine ⟨(cyclicSubmodule D x).zero_mem, ?_, ?_, ?_⟩
  · intro y hy z hz a b
    exact (cyclicSubmodule D x).add_mem
      ((cyclicSubmodule D x).smul_mem a hy)
      ((cyclicSubmodule D x).smul_mem b hz)
  · intro seq hseq y hlim K hK hx
    exact hK.2.2.1 seq (fun n ↦ hseq n K hK hx) y hlim
  · intro y
    constructor
    · intro hy K hK hx
      exact (hK.2.2.2 y).mp (hy K hK hx)
    · intro hUy K hK hx
      exact (hK.2.2.2 y).mpr (hUy K hK hx)

theorem cyclicSubmodule_isClosed (D : HilbertOperatorData.{u}) (x : D.H) :
    IsClosed (cyclicSubmodule D x : Set D.H) := by
  rw [← isSeqClosed_iff_isClosed]
  intro seq y hseq hlim
  exact (cyclicSubmodule_reducing D x).2.2.1 seq hseq y hlim

theorem generator_mem_cyclicSubmodule (D : HilbertOperatorData.{u}) (x : D.H) :
    x ∈ cyclicSubmodule D x := by
  intro K hK hx
  exact hx

noncomputable instance cyclicSubmodule_hasOrthogonalProjection
    (D : HilbertOperatorData.{u}) (x : D.H) :
    (cyclicSubmodule D x).HasOrthogonalProjection := by
  letI : CompleteSpace (cyclicSubmodule D x) :=
    (cyclicSubmodule_isClosed D x).completeSpace_coe
  infer_instance

/-- Orthogonal residual after removing the cyclic component generated by `x`. -/
def cyclicResidual (D : HilbertOperatorData.{u}) (x y : D.H) : D.H :=
  y - (cyclicSubmodule D x).starProjection y

theorem cyclicResidual_mem_orthogonal (D : HilbertOperatorData.{u}) (x y : D.H) :
    cyclicResidual D x y ∈ (cyclicSubmodule D x)ᗮ := by
  exact Submodule.sub_starProjection_mem_orthogonal y

theorem cyclicProjection_mem (D : HilbertOperatorData.{u}) (x y : D.H) :
    (cyclicSubmodule D x).starProjection y ∈ cyclicSubmodule D x :=
  (cyclicSubmodule D x).starProjection_apply_mem y

theorem projection_add_cyclicResidual (D : HilbertOperatorData.{u})
    (x y : D.H) :
    (cyclicSubmodule D x).starProjection y + cyclicResidual D x y = y := by
  simp [cyclicResidual]

theorem cyclicResidual_mem_reducing_orthogonal
    (D : HilbertOperatorData.{u}) (hD : IsUnitary D)
    (S : Submodule ℂ D.H) (hS : IsClosedReducingSubspace D (S : Set D.H))
    (x y : D.H) (hx : x ∈ Sᗮ) (hy : y ∈ Sᗮ) :
    cyclicResidual D x y ∈ Sᗮ := by
  have hSorth : IsClosedReducingSubspace D (Sᗮ : Set D.H) :=
    SpectralRelations.orthogonal_reducing D hD S hS
  have hprojC : (cyclicSubmodule D x).starProjection y ∈ cyclicSubmodule D x :=
    cyclicProjection_mem D x y
  have hprojS : (cyclicSubmodule D x).starProjection y ∈ Sᗮ :=
    hprojC (Sᗮ : Set D.H) hSorth hx
  exact (Sᗮ).sub_mem hy hprojS

theorem cyclicResidual_eq_self_of_orthogonal
    (D : HilbertOperatorData.{u}) (x y : D.H)
    (hy : y ∈ (cyclicSubmodule D x)ᗮ) :
    cyclicResidual D x y = y := by
  let p := (cyclicSubmodule D x).starProjection y
  have hpC : p ∈ cyclicSubmodule D x := cyclicProjection_mem D x y
  have hres : y - p ∈ (cyclicSubmodule D x)ᗮ :=
    cyclicResidual_mem_orthogonal D x y
  have hpOrth : p ∈ (cyclicSubmodule D x)ᗮ := by
    rw [Submodule.mem_orthogonal] at hy hres ⊢
    intro z hz
    have hyz := hy z hz
    have hresz := hres z hz
    rw [inner_sub_right, hyz, zero_sub] at hresz
    exact neg_eq_zero.mp hresz
  rw [Submodule.mem_orthogonal] at hpOrth
  have hinner : @inner ℂ D.H _ p p = 0 := hpOrth p hpC
  have hproj : p = 0 := inner_self_eq_zero.mp hinner
  change (cyclicSubmodule D x).starProjection y = 0 at hproj
  simp [cyclicResidual, hproj]

theorem cyclicResidual_orthogonal (D : HilbertOperatorData.{u})
    (hD : IsUnitary D) (x y : D.H) :
    OrthogonalCyclicSubspaces D x (cyclicResidual D x y) := by
  exact SpectralRelations.cyclic_subspaces_orthogonal_of_mem D
    (cyclicSubmodule D x) x (cyclicResidual D x y)
    (cyclicSubmodule_reducing D x)
    (SpectralRelations.orthogonal_reducing D hD (cyclicSubmodule D x)
      (cyclicSubmodule_reducing D x))
    (generator_mem_cyclicSubmodule D x)
    (cyclicResidual_mem_orthogonal D x y)

/-- Pairwise orthogonality for an indexed vector family. -/
def PairwiseOrthogonalVectors {H : Type*} [NormedAddCommGroup H]
    [InnerProductSpace ℂ H] (z : ℕ → H) : Prop :=
  ∀ i j, i ≠ j → @inner ℂ H _ (z i) (z j) = 0

theorem norm_finset_sum_sq_of_pairwise_orthogonal
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    (z : ℕ → H) (hz : PairwiseOrthogonalVectors z) (s : Finset ℕ) :
    ‖∑ i ∈ s, z i‖ ^ 2 = ∑ i ∈ s, ‖z i‖ ^ 2 := by
  classical
  induction s using Finset.induction_on with
  | empty => simp
  | @insert a s ha ih =>
      rw [Finset.sum_insert ha, Finset.sum_insert ha]
      have hinner : @inner ℂ H _ (z a) (∑ i ∈ s, z i) = 0 := by
        rw [inner_sum]
        apply Finset.sum_eq_zero
        intro i hi
        exact hz a i (by aesop)
      rw [norm_add_sq (𝕜 := ℂ), hinner]
      simp only [map_zero, ih]
      ring

theorem summable_of_pairwise_orthogonal_of_summable_norm_sq
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] (z : ℕ → H) (hz : PairwiseOrthogonalVectors z)
    (hsq : Summable (fun n ↦ ‖z n‖ ^ 2)) : Summable z := by
  rw [summable_iff_vanishing]
  intro e he
  rw [Metric.mem_nhds_iff] at he
  obtain ⟨ε, hε, hball⟩ := he
  have hεsq : 0 < ε ^ 2 := sq_pos_of_pos hε
  have htail := (summable_iff_vanishing.mp hsq)
    (Metric.ball (0 : ℝ) (ε ^ 2)) (Metric.ball_mem_nhds 0 hεsq)
  obtain ⟨s, hs⟩ := htail
  refine ⟨s, ?_⟩
  intro t hts
  apply hball
  rw [Metric.mem_ball, dist_zero_right]
  have hreal := hs t hts
  rw [Metric.mem_ball, Real.dist_eq, sub_zero] at hreal
  have hsum_nonneg : 0 ≤ ∑ b ∈ t, ‖z b‖ ^ 2 := by positivity
  rw [abs_of_nonneg hsum_nonneg] at hreal
  have hnormsq := norm_finset_sum_sq_of_pairwise_orthogonal z hz t
  have hnorm_nonneg : 0 ≤ ‖∑ i ∈ t, z i‖ := norm_nonneg _
  nlinarith [sq_nonneg ‖∑ i ∈ t, z i‖]

theorem norm_tsum_sq_of_pairwise_orthogonal
    {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
    [CompleteSpace H] (z : ℕ → H) (hz : PairwiseOrthogonalVectors z)
    (hsq : Summable (fun n ↦ ‖z n‖ ^ 2)) :
    ‖∑' n, z n‖ ^ 2 = ∑' n, ‖z n‖ ^ 2 := by
  have hsumz := (summable_of_pairwise_orthogonal_of_summable_norm_sq z hz hsq).hasSum
  have hlimz : Tendsto (fun s : Finset ℕ ↦ ‖∑ n ∈ s, z n‖ ^ 2)
      atTop (nhds (‖∑' n, z n‖ ^ 2)) := by
    exact hsumz.norm.pow 2
  have hlimsq := hsq.hasSum
  have hfun : (fun s : Finset ℕ ↦ ‖∑ n ∈ s, z n‖ ^ 2) =
      (fun s : Finset ℕ ↦ ∑ n ∈ s, ‖z n‖ ^ 2) := by
    funext s
    exact norm_finset_sum_sq_of_pairwise_orthogonal z hz s
  rw [hfun] at hlimz
  exact tendsto_nhds_unique hlimz hlimsq

/-- Orthogonal projection onto the cyclic subspace generated by `x n`. -/
def cyclicProjectionFamily (D : HilbertOperatorData.{u})
    (x : ℕ → D.H) (y : D.H) (n : ℕ) : D.H :=
  (cyclicSubmodule D (x n)).starProjection y

theorem cyclicProjectionFamily_mem (D : HilbertOperatorData.{u})
    (x : ℕ → D.H) (y : D.H) (n : ℕ) :
    cyclicProjectionFamily D x y n ∈ cyclicSubmodule D (x n) :=
  cyclicProjection_mem D (x n) y

theorem cyclicProjectionFamily_pairwise_orthogonal
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (horth : ∀ i j, i ≠ j → OrthogonalCyclicSubspaces D (x i) (x j))
    (y : D.H) : PairwiseOrthogonalVectors (cyclicProjectionFamily D x y) := by
  intro i j hij
  exact horth i j hij _ _
    (cyclicProjectionFamily_mem D x y i)
    (cyclicProjectionFamily_mem D x y j)

theorem inner_projection_residual_zero (D : HilbertOperatorData.{u})
    (x : ℕ → D.H) (y : D.H) (n : ℕ) :
    @inner ℂ D.H _ (cyclicProjectionFamily D x y n)
      (y - cyclicProjectionFamily D x y n) = 0 := by
  have hres : y - cyclicProjectionFamily D x y n ∈
      (cyclicSubmodule D (x n))ᗮ :=
    Submodule.sub_starProjection_mem_orthogonal y
  rw [Submodule.mem_orthogonal] at hres
  exact hres _ (cyclicProjectionFamily_mem D x y n)

theorem inner_projection_finset_residual_zero
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (horth : ∀ i j, i ≠ j → OrthogonalCyclicSubspaces D (x i) (x j))
    (y : D.H) (s : Finset ℕ) :
    @inner ℂ D.H _ (∑ n ∈ s, cyclicProjectionFamily D x y n)
      (y - ∑ n ∈ s, cyclicProjectionFamily D x y n) = 0 := by
  rw [sum_inner]
  apply Finset.sum_eq_zero
  intro i hi
  rw [inner_sub_right, inner_sum]
  have hdiag := inner_projection_residual_zero D x y i
  rw [inner_sub_right] at hdiag
  rw [show ∑ j ∈ s, @inner ℂ D.H _ (cyclicProjectionFamily D x y i)
      (cyclicProjectionFamily D x y j) =
      @inner ℂ D.H _ (cyclicProjectionFamily D x y i)
        (cyclicProjectionFamily D x y i) by
    rw [Finset.sum_eq_single i]
    · intro j hj hji
      exact horth i j hji.symm _ _
        (cyclicProjectionFamily_mem D x y i)
        (cyclicProjectionFamily_mem D x y j)
    · intro hnot
      exact (hnot hi).elim]
  exact hdiag

theorem cyclicProjectionFamily_bessel
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (horth : ∀ i j, i ≠ j → OrthogonalCyclicSubspaces D (x i) (x j))
    (y : D.H) (s : Finset ℕ) :
    ∑ n ∈ s, ‖cyclicProjectionFamily D x y n‖ ^ 2 ≤ ‖y‖ ^ 2 := by
  let q := ∑ n ∈ s, cyclicProjectionFamily D x y n
  have hqorth : @inner ℂ D.H _ q (y - q) = 0 :=
    inner_projection_finset_residual_zero D x horth y s
  have hpyth := norm_add_sq_eq_norm_sq_add_norm_sq_of_inner_eq_zero q (y - q) hqorth
  have hy : q + (y - q) = y := by abel
  rw [hy] at hpyth
  have hqnorm := norm_finset_sum_sq_of_pairwise_orthogonal
    (cyclicProjectionFamily D x y)
    (cyclicProjectionFamily_pairwise_orthogonal D x horth y) s
  rw [show ‖q‖ * ‖q‖ = ‖q‖ ^ 2 by ring,
    show ‖y‖ * ‖y‖ = ‖y‖ ^ 2 by ring, hqnorm] at hpyth
  nlinarith [sq_nonneg ‖y - q‖]

theorem cyclicProjectionFamily_norm_sq_summable
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (horth : ∀ i j, i ≠ j → OrthogonalCyclicSubspaces D (x i) (x j))
    (y : D.H) : Summable (fun n ↦ ‖cyclicProjectionFamily D x y n‖ ^ 2) := by
  apply summable_of_sum_le (fun n ↦ sq_nonneg ‖cyclicProjectionFamily D x y n‖)
  intro s
  exact cyclicProjectionFamily_bessel D x horth y s

theorem cyclicProjectionFamily_summable
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (horth : ∀ i j, i ≠ j → OrthogonalCyclicSubspaces D (x i) (x j))
    (y : D.H) : Summable (cyclicProjectionFamily D x y) :=
  summable_of_pairwise_orthogonal_of_summable_norm_sq
    (cyclicProjectionFamily D x y)
    (cyclicProjectionFamily_pairwise_orthogonal D x horth y)
    (cyclicProjectionFamily_norm_sq_summable D x horth y)

theorem finite_projection_residual_mem_orthogonal
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (horth : ∀ i j, i ≠ j → OrthogonalCyclicSubspaces D (x i) (x j))
    (y : D.H) (s : Finset ℕ) (n : ℕ) (hn : n ∈ s) :
    y - ∑ i ∈ s, cyclicProjectionFamily D x y i ∈
      (cyclicSubmodule D (x n))ᗮ := by
  rw [Submodule.mem_orthogonal]
  intro a ha
  rw [inner_sub_right, inner_sum]
  have hres : y - cyclicProjectionFamily D x y n ∈
      (cyclicSubmodule D (x n))ᗮ :=
    Submodule.sub_starProjection_mem_orthogonal y
  rw [Submodule.mem_orthogonal] at hres
  have hdiag := hres a ha
  rw [inner_sub_right] at hdiag
  rw [show ∑ i ∈ s, @inner ℂ D.H _ a (cyclicProjectionFamily D x y i) =
      @inner ℂ D.H _ a (cyclicProjectionFamily D x y n) by
    rw [Finset.sum_eq_single n]
    · intro i hi hin
      exact horth n i hin.symm a _ ha
        (cyclicProjectionFamily_mem D x y i)
    · intro hnot
      exact (hnot hn).elim]
  exact hdiag

theorem tsum_projection_residual_mem_orthogonal
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (horth : ∀ i j, i ≠ j → OrthogonalCyclicSubspaces D (x i) (x j))
    (y : D.H) (n : ℕ) :
    y - ∑' i, cyclicProjectionFamily D x y i ∈
      (cyclicSubmodule D (x n))ᗮ := by
  let z := cyclicProjectionFamily D x y
  have hzsum : Summable z := cyclicProjectionFamily_summable D x horth y
  have hlim : Tendsto (fun N ↦ y - ∑ i ∈ Finset.range N, z i)
      atTop (nhds (y - ∑' i, z i)) :=
    tendsto_const_nhds.sub hzsum.hasSum.tendsto_sum_nat
  have hclosed : IsClosed ((cyclicSubmodule D (x n))ᗮ : Set D.H) :=
    Submodule.isClosed_orthogonal _
  rw [← isSeqClosed_iff_isClosed] at hclosed
  refine hclosed (x := fun N ↦ y - ∑ i ∈ Finset.range (N + n + 1), z i)
    (p := y - ∑' i, z i) ?_ ?_
  · intro N
    apply finite_projection_residual_mem_orthogonal D x horth y
    simp only [Finset.mem_range]
    omega
  · exact hlim.comp (tendsto_add_atTop_nat (n + 1))

theorem orthogonal_to_all_cyclic_eq_zero
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (hdec : IsOrthogonalCyclicDecomposition D x)
    (r : D.H) (hr : ∀ n, r ∈ (cyclicSubmodule D (x n))ᗮ) : r = 0 := by
  by_contra hr0
  have hrpos : 0 < ‖r‖ := norm_pos_iff.mpr hr0
  obtain ⟨s, z, hz, hclose⟩ := hdec.2 r ‖r‖ hrpos
  let w : D.H := ∑ n ∈ s, z n
  have hinner : @inner ℂ D.H _ w r = 0 := by
    dsimp [w]
    rw [sum_inner]
    apply Finset.sum_eq_zero
    intro n hn
    have hrn := hr n
    rw [Submodule.mem_orthogonal] at hrn
    exact hrn (z n) (hz n hn)
  have hinner' : @inner ℂ D.H _ r (-w) = 0 := by
    rw [inner_neg_right, ← inner_conj_symm, hinner]
    simp
  have hnorm := norm_add_sq (𝕜 := ℂ) r (-w)
  rw [hinner'] at hnorm
  simp only [map_zero, norm_neg] at hnorm
  have hle : ‖r‖ ^ 2 ≤ ‖r - w‖ ^ 2 := by
    rw [show r - w = r + -w by abel, hnorm]
    nlinarith [sq_nonneg ‖w‖]
  have hnorm_nonneg : 0 ≤ ‖r - w‖ := norm_nonneg _
  have hrnorm_nonneg : 0 ≤ ‖r‖ := norm_nonneg _
  have : ‖r‖ ≤ ‖r - w‖ := by nlinarith
  exact (not_lt_of_ge this) hclose

theorem tsum_cyclicProjectionFamily_eq
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (hdec : IsOrthogonalCyclicDecomposition D x) (y : D.H) :
    ∑' n, cyclicProjectionFamily D x y n = y := by
  let p := ∑' n, cyclicProjectionFamily D x y n
  have hres : y - p = 0 := orthogonal_to_all_cyclic_eq_zero D x hdec (y - p)
    (fun n ↦ tsum_projection_residual_mem_orthogonal D x hdec.1 y n)
  exact (sub_eq_zero.mp hres).symm

/-- Pairwise orthogonal cyclic subspaces form a decomposition as soon as their
common orthogonal complement is trivial. -/
theorem orthogonalCyclicDecomposition_of_complete
    (D : HilbertOperatorData.{u}) (x : ℕ → D.H)
    (horth : ∀ i j, i ≠ j → OrthogonalCyclicSubspaces D (x i) (x j))
    (hcomplete : ∀ r : D.H,
      (∀ n, r ∈ (cyclicSubmodule D (x n))ᗮ) → r = 0) :
    IsOrthogonalCyclicDecomposition D x := by
  refine ⟨horth, ?_⟩
  intro y ε hε
  let p : D.H := ∑' n, cyclicProjectionFamily D x y n
  have hp : p = y := by
    have hres : y - p = 0 := hcomplete (y - p)
      (fun n ↦ tsum_projection_residual_mem_orthogonal D x horth y n)
    exact (sub_eq_zero.mp hres).symm
  have hsum := (cyclicProjectionFamily_summable D x horth y).hasSum
  have hlim : Tendsto
      (fun N ↦ ∑ n ∈ Finset.range N, cyclicProjectionFamily D x y n)
      atTop (nhds y) := by
    have ht := hsum.tendsto_sum_nat
    have hp' : (∑' n, cyclicProjectionFamily D x y n) = y := hp
    rw [hp'] at ht
    exact ht
  have hevent : ∀ᶠ N in atTop,
      ‖y - ∑ n ∈ Finset.range N, cyclicProjectionFamily D x y n‖ < ε := by
    have hcont : Tendsto
        (fun z : D.H ↦ ‖y - z‖) (nhds y) (nhds ‖y - y‖) :=
      continuousAt_const.sub continuousAt_id |>.norm
    have hz : ‖y - y‖ = 0 := by rw [sub_self, norm_zero]
    rw [hz] at hcont
    have hev := (hcont.comp hlim) (Metric.ball_mem_nhds 0 hε)
    filter_upwards [hev] with N hN
    change ‖y - ∑ n ∈ Finset.range N,
      cyclicProjectionFamily D x y n‖ ∈ Metric.ball 0 ε at hN
    rw [Metric.mem_ball, dist_zero_right] at hN
    simpa only [Real.norm_eq_abs, abs_of_nonneg (norm_nonneg _)] using hN
  obtain ⟨N, hN⟩ := Filter.eventually_atTop.1 hevent
  refine ⟨Finset.range N, cyclicProjectionFamily D x y, ?_, hN N le_rfl⟩
  intro n hn
  exact cyclicProjectionFamily_mem D x y n

end Chapter02.SpectralDecomposition
