import Chapter02.Common

open Classical Set MeasureTheory

noncomputable section

namespace Chapter02.BHKOrbitCoding

universe u

/-- A universe-correct standard-Borel carrier for a Bool-valued orbit code. -/
abbrev OrbitCodeTarget : Type u := (ℕ → Bool) × ULift.{u} Unit

/-- The forward orbit of `A`, viewed as a countable family of measurable sets. -/
def orbitSetFamily (M : System.{u}) (A : Set M.X) (n : ℕ) : Set M.X :=
  preimageIter M n A

/-- The Bool itinerary of a point under the forward orbit of `T`. -/
def orbitCode (M : System.{u}) (A : Set M.X) (x : M.X) :
    OrbitCodeTarget :=
  (fun n => decide (x ∈ orbitSetFamily M A n), ULift.up ())

/-- The left shift, with the universe-lifting coordinate left unchanged. -/
def liftedBoolShift (y : OrbitCodeTarget) : OrbitCodeTarget :=
  (fun n => y.1 (n + 1), y.2)

/-- The pushforward system generated by the forward `A`-itinerary. -/
def orbitCodeSystem (M : System.{u}) (A : Set M.X) : System.{u} where
  X := OrbitCodeTarget
  measurableSpace := inferInstance
  μ := Measure.map (orbitCode M A) M.μ
  T := liftedBoolShift

theorem orbitSetFamily_measurable
    (M : System.{u}) (hM : Chapter01.IsMeasurePreservingSystem M)
    (A : Set M.X) (hA : MeasurableSet A) (n : ℕ) :
    MeasurableSet (orbitSetFamily M A n) := by
  exact hA.preimage (hM.2.measurable.iterate n)

theorem orbitCode_measurable
    (M : System.{u}) (hM : Chapter01.IsMeasurePreservingSystem M)
    (A : Set M.X) (hA : MeasurableSet A) :
    Measurable (orbitCode M A) := by
  change Measurable fun x =>
    ((fun n => decide (x ∈ orbitSetFamily M A n)), ULift.up ())
  have hfirst : Measurable fun x =>
      (fun n => decide (x ∈ orbitSetFamily M A n)) := by
    rw [measurable_pi_iff]
    intro n
    apply measurable_to_bool
    have heq :
        (fun x => decide (x ∈ orbitSetFamily M A n)) ⁻¹'
            ({true} : Set Bool) =
          orbitSetFamily M A n := by
      ext x
      simp
    rw [heq]
    exact orbitSetFamily_measurable M hM A hA n
  exact hfirst.prod measurable_const

theorem liftedBoolShift_measurable :
    Measurable (liftedBoolShift : OrbitCodeTarget → OrbitCodeTarget) := by
  apply Measurable.prod
  · rw [measurable_pi_iff]
    intro n
    exact measurable_pi_apply (n + 1) |>.comp measurable_fst
  · exact measurable_snd

theorem orbitCode_intertwines
    (M : System.{u}) (A : Set M.X) :
    (fun x => orbitCode M A (M.T x)) =
      (fun x => liftedBoolShift (orbitCode M A x)) := by
  funext x
  apply Prod.ext
  · funext n
    simp only [orbitCode, liftedBoolShift, orbitSetFamily, preimageIter,
      Chapter01.iterateMap, Set.mem_preimage]
    rw [Function.iterate_succ_apply]
  · rfl

theorem orbitCodeSystem_measurePreserving
    (M : System.{u}) (hM : Chapter01.IsMeasurePreservingSystem M)
    (A : Set M.X) (hA : MeasurableSet A) :
    Chapter01.IsMeasurePreservingSystem (orbitCodeSystem M A) := by
  let π := orbitCode M A
  let R := liftedBoolShift
  have hπ : Measurable π := orbitCode_measurable M hM A hA
  have hR : Measurable R := liftedBoolShift_measurable
  have hinter : (fun x => π (M.T x)) =ᵐ[M.μ] (fun x => R (π x)) :=
    Filter.Eventually.of_forall fun x =>
      congrFun (orbitCode_intertwines M A) x
  constructor
  · apply IsProbabilityMeasure.mk
    change (Measure.map π M.μ) Set.univ = 1
    rw [Measure.map_apply hπ MeasurableSet.univ]
    exact hM.1.measure_univ
  · refine ⟨hR, ?_⟩
    change Measure.map R (Measure.map π M.μ) = Measure.map π M.μ
    rw [Measure.map_map hR hπ]
    calc
      Measure.map (R ∘ π) M.μ =
          Measure.map (π ∘ M.T) M.μ := Measure.map_congr hinter.symm
      _ = Measure.map π (Measure.map M.T M.μ) := by
        rw [Measure.map_map hπ hM.2.measurable]
      _ = Measure.map π M.μ := by rw [hM.2.map_eq]

theorem orbitCode_factorMap
    (M : System.{u}) (hM : Chapter01.IsMeasurePreservingSystem M)
    (A : Set M.X) (hA : MeasurableSet A) :
    Chapter01.IsFactorMap M (orbitCodeSystem M A) (orbitCode M A) := by
  let N := orbitCodeSystem M A
  let π := orbitCode M A
  have hN := orbitCodeSystem_measurePreserving M hM A hA
  have hπ : Measurable π := orbitCode_measurable M hM A hA
  have hMuniv : Set.univ ∈ M.𝓧 := by
    change MeasurableSet Set.univ
    exact MeasurableSet.univ
  have hNuniv : Set.univ ∈ N.𝓧 := by
    change @MeasurableSet OrbitCodeTarget inferInstance Set.univ
    exact MeasurableSet.univ
  refine ⟨hM, hN, Set.univ, Set.univ, hM.1.measure_univ,
    hN.1.measure_univ, (fun x _ => Set.mem_univ (M.T x)),
    (fun y _ => Set.mem_univ (N.T y)), ?_, ?_⟩
  · refine ⟨hMuniv, hNuniv, hM.1.measure_univ, hN.1.measure_univ,
      (fun x _ => Set.mem_univ (π x)), ?_⟩
    intro B hB
    have hBm : MeasurableSet B := hB
    constructor
    · change MeasurableSet (Set.univ ∩ π ⁻¹' (B ∩ Set.univ))
      simpa using hBm.preimage hπ
    · change M.μ (Set.univ ∩ π ⁻¹' (B ∩ Set.univ)) = N.μ (B ∩ Set.univ)
      change M.μ (Set.univ ∩ π ⁻¹' (B ∩ Set.univ)) =
        (Measure.map π M.μ) (B ∩ Set.univ)
      simpa only [Set.inter_univ, Set.univ_inter] using
        (Measure.map_apply (μ := M.μ) hπ hBm).symm
  · intro x _
    exact congrFun (orbitCode_intertwines M A) x

theorem orbitCodeSystem_ergodic
    (M : System.{u}) (hM : IsErgodic M)
    (A : Set M.X) (hA : MeasurableSet A) :
    IsErgodic (orbitCodeSystem M A) := by
  let N := orbitCodeSystem M A
  let π := orbitCode M A
  have hN := orbitCodeSystem_measurePreserving M hM.1 A hA
  have hπ : Measurable π := orbitCode_measurable M hM.1 A hA
  refine ⟨hN, ?_⟩
  intro B hB hBinv
  have hpre : MeasurableSet (π ⁻¹' B) := hB.preimage hπ
  have hset :
      Chapter00.symmDiff (M.T ⁻¹' (π ⁻¹' B)) (π ⁻¹' B) =
        π ⁻¹' (Chapter00.symmDiff (N.T ⁻¹' B) B) := by
    ext x
    simp only [Chapter00.symmDiff, Set.mem_union, Set.mem_diff,
      Set.mem_preimage]
    rw [show π (M.T x) = N.T (π x) by
      exact congrFun (orbitCode_intertwines M A) x]
  have hinv : M.μ (Chapter00.symmDiff (M.T ⁻¹' (π ⁻¹' B)) (π ⁻¹' B)) = 0 := by
    rw [hset, ← Measure.map_apply hπ]
    · exact hBinv
    · exact ((hB.preimage hN.2.measurable).diff hB).union
        (hB.diff (hB.preimage hN.2.measurable))
  have hmeasure : N.μ B = M.μ (π ⁻¹' B) :=
    Measure.map_apply hπ hB
  rcases hM.2 (π ⁻¹' B) hpre hinv with hzero | hone
  · left
    rw [hmeasure]
    exact hzero
  · right
    rw [hmeasure]
    exact hone

/-- The coordinate-zero cylinder representing the original set `A`. -/
def codedSet : Set OrbitCodeTarget :=
  {y | y.1 0 = true}

theorem codedSet_measurable : MeasurableSet codedSet := by
  change MeasurableSet ((fun y : OrbitCodeTarget => y.1 0) ⁻¹' {true})
  exact MeasurableSet.singleton true |>.preimage
    (measurable_pi_apply 0 |>.comp measurable_fst)

theorem liftedBoolShift_iterate_fst
    (n m : ℕ) (y : OrbitCodeTarget) :
    ((liftedBoolShift^[n]) y).1 m = y.1 (m + n) := by
  induction n generalizing m with
  | zero => simp
  | succ n ih =>
      rw [Function.iterate_succ_apply']
      simp only [liftedBoolShift]
      simpa [Nat.add_assoc, Nat.add_comm, Nat.add_left_comm] using
        (ih (m + 1))

theorem orbitCode_preimage_iterate_codedSet
    (M : System.{u}) (A : Set M.X) (n : ℕ) :
    orbitCode M A ⁻¹'
        preimageIter (orbitCodeSystem M A) n codedSet =
      preimageIter M n A := by
  ext x
  simp only [Set.mem_preimage, preimageIter, Chapter01.iterateMap, codedSet,
    orbitCodeSystem]
  change ((liftedBoolShift^[n]) (orbitCode M A x)).1 0 = true ↔
    (M.T^[n]) x ∈ A
  rw [liftedBoolShift_iterate_fst]
  simp [orbitCode, orbitSetFamily, preimageIter, Chapter01.iterateMap]

theorem orbitCode_preimage_codedSet
    (M : System.{u}) (A : Set M.X) :
    orbitCode M A ⁻¹' codedSet = A := by
  simpa [preimageIter] using orbitCode_preimage_iterate_codedSet M A 0

theorem codedSet_measure
    (M : System.{u}) (hM : Chapter01.IsMeasurePreservingSystem M)
    (A : Set M.X) (hA : MeasurableSet A) :
    (orbitCodeSystem M A).μ codedSet = M.μ A := by
  change (Measure.map (orbitCode M A) M.μ) codedSet = M.μ A
  calc
    (Measure.map (orbitCode M A) M.μ) codedSet =
        M.μ (orbitCode M A ⁻¹' codedSet) :=
      Measure.map_apply (μ := M.μ) (orbitCode_measurable M hM A hA)
        codedSet_measurable
    _ = M.μ A := by rw [orbitCode_preimage_codedSet]

theorem coded_triple_preimage
    (M : System.{u}) (A : Set M.X) (n : ℕ) :
    orbitCode M A ⁻¹'
        (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
          preimageIter (orbitCodeSystem M A) (2 * n) codedSet) =
      A ∩ preimageIter M n A ∩ preimageIter M (2 * n) A := by
  rw [Set.preimage_inter, Set.preimage_inter,
    orbitCode_preimage_codedSet,
    orbitCode_preimage_iterate_codedSet,
    orbitCode_preimage_iterate_codedSet]

theorem coded_fourfold_preimage
    (M : System.{u}) (A : Set M.X) (n : ℕ) :
    orbitCode M A ⁻¹'
        (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
          preimageIter (orbitCodeSystem M A) (2 * n) codedSet ∩
          preimageIter (orbitCodeSystem M A) (3 * n) codedSet) =
      A ∩ preimageIter M n A ∩ preimageIter M (2 * n) A ∩
        preimageIter M (3 * n) A := by
  rw [Set.preimage_inter, Set.preimage_inter, Set.preimage_inter,
    orbitCode_preimage_codedSet,
    orbitCode_preimage_iterate_codedSet,
    orbitCode_preimage_iterate_codedSet,
    orbitCode_preimage_iterate_codedSet]

theorem coded_triple_measure
    (M : System.{u}) (hM : Chapter01.IsMeasurePreservingSystem M)
    (A : Set M.X) (hA : MeasurableSet A) (n : ℕ) :
    (orbitCodeSystem M A).μ
        (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
          preimageIter (orbitCodeSystem M A) (2 * n) codedSet) =
      M.μ (A ∩ preimageIter M n A ∩ preimageIter M (2 * n) A) := by
  have hN := orbitCodeSystem_measurePreserving M hM A hA
  have hC : MeasurableSet
      (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
        preimageIter (orbitCodeSystem M A) (2 * n) codedSet) := by
    exact (codedSet_measurable.inter
      (codedSet_measurable.preimage (hN.2.measurable.iterate n))).inter
      (codedSet_measurable.preimage (hN.2.measurable.iterate (2 * n)))
  change (Measure.map (orbitCode M A) M.μ) _ = _
  rw [Measure.map_apply (orbitCode_measurable M hM A hA) hC,
    coded_triple_preimage]

theorem coded_fourfold_measure
    (M : System.{u}) (hM : Chapter01.IsMeasurePreservingSystem M)
    (A : Set M.X) (hA : MeasurableSet A) (n : ℕ) :
    (orbitCodeSystem M A).μ
        (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
          preimageIter (orbitCodeSystem M A) (2 * n) codedSet ∩
          preimageIter (orbitCodeSystem M A) (3 * n) codedSet) =
      M.μ (A ∩ preimageIter M n A ∩ preimageIter M (2 * n) A ∩
        preimageIter M (3 * n) A) := by
  have hN := orbitCodeSystem_measurePreserving M hM A hA
  have hC : MeasurableSet
      (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
        preimageIter (orbitCodeSystem M A) (2 * n) codedSet ∩
        preimageIter (orbitCodeSystem M A) (3 * n) codedSet) := by
    exact ((codedSet_measurable.inter
      (codedSet_measurable.preimage (hN.2.measurable.iterate n))).inter
      (codedSet_measurable.preimage (hN.2.measurable.iterate (2 * n)))).inter
      (codedSet_measurable.preimage (hN.2.measurable.iterate (3 * n)))
  change (Measure.map (orbitCode M A) M.μ) _ = _
  rw [Measure.map_apply (orbitCode_measurable M hM A hA) hC,
    coded_fourfold_preimage]

/-- The three- and four-term Khintchine conclusions for the coded cylinder
transfer exactly back to the original set. -/
theorem multipleKhintchine_transfer
    (M : System.{u}) (hM : IsErgodic M)
    (A : Set M.X) (hA : MeasurableSet A) (ε : ℝ)
    (hcode :
      IsSyndetic {n : ℕ |
        realMeasure (orbitCodeSystem M A)
            (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
              preimageIter (orbitCodeSystem M A) (2 * n) codedSet) >
          (realMeasure (orbitCodeSystem M A) codedSet) ^ 3 - ε} ∧
      IsSyndetic {n : ℕ |
        realMeasure (orbitCodeSystem M A)
            (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
              preimageIter (orbitCodeSystem M A) (2 * n) codedSet ∩
              preimageIter (orbitCodeSystem M A) (3 * n) codedSet) >
          (realMeasure (orbitCodeSystem M A) codedSet) ^ 4 - ε}) :
    IsSyndetic {n : ℕ |
      realMeasure M
          (A ∩ preimageIter M n A ∩ preimageIter M (2 * n) A) >
        (realMeasure M A) ^ 3 - ε} ∧
    IsSyndetic {n : ℕ |
      realMeasure M
          (A ∩ preimageIter M n A ∩ preimageIter M (2 * n) A ∩
            preimageIter M (3 * n) A) >
        (realMeasure M A) ^ 4 - ε} := by
  have hbase :
      realMeasure (orbitCodeSystem M A) codedSet = realMeasure M A := by
    exact congrArg ENNReal.toReal (codedSet_measure M hM.1 A hA)
  have htriple (n : ℕ) :
      realMeasure (orbitCodeSystem M A)
          (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
            preimageIter (orbitCodeSystem M A) (2 * n) codedSet) =
        realMeasure M
          (A ∩ preimageIter M n A ∩ preimageIter M (2 * n) A) := by
    exact congrArg ENNReal.toReal (coded_triple_measure M hM.1 A hA n)
  have hfourfold (n : ℕ) :
      realMeasure (orbitCodeSystem M A)
          (codedSet ∩ preimageIter (orbitCodeSystem M A) n codedSet ∩
            preimageIter (orbitCodeSystem M A) (2 * n) codedSet ∩
            preimageIter (orbitCodeSystem M A) (3 * n) codedSet) =
        realMeasure M
          (A ∩ preimageIter M n A ∩ preimageIter M (2 * n) A ∩
            preimageIter M (3 * n) A) := by
    exact congrArg ENNReal.toReal (coded_fourfold_measure M hM.1 A hA n)
  constructor
  · convert hcode.1 using 1
    ext n
    simp only [Set.mem_setOf_eq]
    rw [htriple n, hbase]
  · convert hcode.2 using 1
    ext n
    simp only [Set.mem_setOf_eq]
    rw [hfourfold n, hbase]

end Chapter02.BHKOrbitCoding
