import Chapter02.Recurrence.MultipleKhintchineUniform
import Chapter02.Recurrence.MultipleKhintchineCartesianCharacteristic

open Classical Filter Set

noncomputable section

namespace Chapter02.MultipleKhintchineTriple

universe u

/-- Once the triple characteristic-factor error is zero in uniform density,
the already checked compact recurrence and BHK's finite counting lemma give
the exact cubic Khintchine conclusion. -/
theorem triple_syndetic_of_uniformDensity_characteristic
    (M : System.{u}) (hM : IsErgodic M)
    (A : Set M.X) (hA : MeasurableSet A)
    (hchar :
      MultipleKhintchineSyndetic.TendsToZeroInUniformDensity
        (fun n ↦
          MultipleKhintchineSyndetic.tripleCorrelation M A n -
            ForwardKroneckerFactor.forwardKroneckerTripleCorrelation
              M hM A hA n))
    (ε : ℝ) (hε : 0 < ε) :
    IsSyndetic {n : ℕ |
      MultipleKhintchineSyndetic.tripleCorrelation M A n >
        (realMeasure M A) ^ 3 - ε} := by
  let c : ℝ := (realMeasure M A) ^ 3 - ε
  let η : ℝ := ε / 2
  have hη : 0 < η := by
    dsimp [η]
    positivity
  have hcompact :
      IsSyndetic {n : ℕ |
        ForwardKroneckerFactor.forwardKroneckerTripleCorrelation
            M hM A hA n >
          c + η} := by
    have hs :=
      ForwardKroneckerFactor.forwardKroneckerTripleCorrelation_syndetic
        M hM A hA (ε / 2) (by positivity)
    dsimp [c, η]
    rw [show (realMeasure M A) ^ 3 - ε + ε / 2 =
      (realMeasure M A) ^ 3 - ε / 2 by ring]
    exact hs
  exact
    MultipleKhintchineSyndetic.isSyndetic_superlevel_of_uniformDensity_close
      (MultipleKhintchineSyndetic.tripleCorrelation M A)
      (ForwardKroneckerFactor.forwardKroneckerTripleCorrelation M hM A hA)
      c η hη hcompact hchar

/-- The three-term clause of BHK Theorem 1.2, reduced without changing its
statement to the two Cartesian-square cancellation assertions generated by
the forward-Kronecker residual. -/
theorem triple_syndetic_of_cartesian_characteristic
    (M : System.{u}) (hM : IsErgodic M)
    (A : Set M.X) (hA : MeasurableSet A)
    (hright :
      MultipleKhintchineCartesian.CartesianTripleUniformZero M
        (fun x ↦ star
          (MultipleKhintchineCharacteristic.indicatorLp M hM.1 A hA x))
        (fun x ↦
          MultipleKhintchineCharacteristic.indicatorLp M hM.1 A hA x)
        (fun x ↦
          (MultipleKhintchineCharacteristic.indicatorLp M hM.1 A hA -
            ForwardKroneckerFactor.forwardKroneckerIndicatorLp
              M hM A hA) x))
    (hleft :
      MultipleKhintchineCartesian.CartesianTripleUniformZero M
        (fun x ↦ star
          (MultipleKhintchineCharacteristic.indicatorLp M hM.1 A hA x))
        (fun x ↦
          (MultipleKhintchineCharacteristic.indicatorLp M hM.1 A hA -
            ForwardKroneckerFactor.forwardKroneckerIndicatorLp
              M hM A hA) x)
        (fun x ↦
          ForwardKroneckerFactor.forwardKroneckerIndicatorLp
            M hM A hA x))
    (ε : ℝ) (hε : 0 < ε) :
    IsSyndetic {n : ℕ |
      MultipleKhintchineSyndetic.tripleCorrelation M A n >
        (realMeasure M A) ^ 3 - ε} := by
  apply triple_syndetic_of_uniformDensity_characteristic M hM A hA
  · exact
      Chapter02.MultipleKhintchineCartesianCharacteristic.tripleCharacteristic_uniformDensity_of_cartesian
        M hM A hA hright hleft
  · exact hε

end Chapter02.MultipleKhintchineTriple
