import Chapter02.HallPetresco.HallPetrescoLattice
import Mathlib.GroupTheory.Commutator.Basic

open Classical MeasureTheory

noncomputable section

namespace Chapter02.HallPetrescoReducedQuotient

open Chapter02.HallPetrescoTwoStepGroup
open Chapter02.HallPetrescoLattice

universe u v

/-- The diagonal direction as an element of the actual Hall--Petresco
subgroup. -/
def diagonalElement
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) (g : H) :
    subgroup N :=
  ⟨diagonal g, diagonal_mem_subgroup N g⟩

/-- The linear direction coming from the chosen compact central torus. -/
def linearCentralElement
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (z : Fin N.torusDim → Circle) :
    subgroup N :=
  ⟨linear (N.centralHom z), linear_mem_subgroup N (N.centralHom z)⟩

/-- Generators of the directions averaged out in BHK's reduced
Hall--Petresco nilmanifold. -/
def averagingGenerators
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    Set (subgroup N) :=
  Set.range (diagonalElement N) ∪ Set.range (linearCentralElement N)

/-- The closed normal subgroup generated by the diagonal direction and the
linear compact-central direction.  Taking the normal closure inside the
actual Hall--Petresco group automatically includes all commutator directions
created by conjugation, without assuming that the chosen central torus is
definitionally the whole commutator subgroup. -/
def averagingNormalSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    Subgroup (subgroup N) :=
  (Subgroup.normalClosure (averagingGenerators N)).topologicalClosure

instance averagingNormalSubgroup_normal
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    (averagingNormalSubgroup N).Normal := by
  unfold averagingNormalSubgroup
  letI : (Subgroup.normalClosure (averagingGenerators N)).Normal :=
    Subgroup.normalClosure_normal
  exact Subgroup.is_normal_topologicalClosure _

theorem isClosed_averagingNormalSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    IsClosed (averagingNormalSubgroup N : Set (subgroup N)) :=
  Subgroup.isClosed_topologicalClosure _

instance averagingNormalSubgroup_isClosed
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    IsClosed (averagingNormalSubgroup N : Set (subgroup N)) :=
  isClosed_averagingNormalSubgroup N

theorem diagonalElement_mem_averagingNormalSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) (g : H) :
    diagonalElement N g ∈ averagingNormalSubgroup N := by
  apply Subgroup.le_topologicalClosure
  apply Subgroup.subset_normalClosure
  exact Or.inl ⟨g, rfl⟩

theorem linearCentralElement_mem_averagingNormalSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (z : Fin N.torusDim → Circle) :
    linearCentralElement N z ∈ averagingNormalSubgroup N := by
  apply Subgroup.le_topologicalClosure
  apply Subgroup.subset_normalClosure
  exact Or.inr ⟨z, rfl⟩

/-- Every linear direction from the full second lower-central subgroup is
removed.  The `centralHom_range` field identifies the chosen torus with
`G₂ = [H,H]`, so this is exactly the linear direction in BHK's `Ḡ`. -/
theorem linearCommutator_mem_averagingNormalSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (c : H) (hc : c ∈ _root_.commutator H) :
    (⟨linear c, linear_mem_subgroup N c⟩ : subgroup N) ∈
      averagingNormalSubgroup N := by
  have hc' : c ∈ N.centralHom.range := by
    rw [N.centralHom_range]
    exact hc
  obtain ⟨z, rfl⟩ := hc'
  exact linearCentralElement_mem_averagingNormalSubgroup N z

/-- The reduced Hall--Petresco group `K = G̃ / Ḡ`. -/
abbrev ReducedGroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :=
  (subgroup N) ⧸ averagingNormalSubgroup N

@[simp]
theorem reduced_mk_diagonalElement
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) (g : H) :
    QuotientGroup.mk' (averagingNormalSubgroup N)
        (diagonalElement N g) =
      (1 : ReducedGroup N) :=
  (QuotientGroup.eq_one_iff _).mpr
    (diagonalElement_mem_averagingNormalSubgroup N g)

@[simp]
theorem reduced_mk_linearCentralElement
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (z : Fin N.torusDim → Circle) :
    QuotientGroup.mk' (averagingNormalSubgroup N)
        (linearCentralElement N z) =
      (1 : ReducedGroup N) :=
  (QuotientGroup.eq_one_iff _).mpr
    (linearCentralElement_mem_averagingNormalSubgroup N z)

/-- Image of the actual four-coordinate lattice in the reduced group. -/
def reducedLattice
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) :
    Subgroup (ReducedGroup N) :=
  (subgroupLattice N Γ).map
    (QuotientGroup.mk' (averagingNormalSubgroup N))

/-- The actual reduced homogeneous-space carrier
`Y = (G̃ / Ḡ) / p(Λ̃)` from BHK Lemma 7.1. -/
abbrev ReducedQuotient
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) :=
  (ReducedGroup N) ⧸ reducedLattice N Γ

/-- The canonical factor map from the unreduced Hall--Petresco homogeneous
space to the reduced homogeneous space. -/
def fullToReduced
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) :
    Quotient N Γ → ReducedQuotient N Γ :=
  Quotient.map'
    (fun g : subgroup N ↦
      QuotientGroup.mk' (averagingNormalSubgroup N) g)
    (by
      intro g h hgh
      apply QuotientGroup.leftRel_apply.mpr
      change
        QuotientGroup.mk' (averagingNormalSubgroup N) (g⁻¹ * h) ∈
          reducedLattice N Γ
      exact ⟨g⁻¹ * h, QuotientGroup.leftRel_apply.mp hgh, rfl⟩)

@[simp]
theorem fullToReduced_mk
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (g : subgroup N) :
    fullToReduced N Γ (QuotientGroup.mk g : Quotient N Γ) =
      (QuotientGroup.mk (s := reducedLattice N Γ)
        (QuotientGroup.mk' (averagingNormalSubgroup N) g) :
          ReducedQuotient N Γ) :=
  Quotient.map'_mk'' _ _ _

theorem continuous_fullToReduced
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) :
    Continuous (fullToReduced N Γ) := by
  unfold fullToReduced Quotient.map'
  apply Continuous.quotient_lift
  exact
    (QuotientGroup.continuous_mk (N := reducedLattice N Γ)).comp
      (QuotientGroup.continuous_mk (N := averagingNormalSubgroup N))

theorem surjective_fullToReduced
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) :
    Function.Surjective (fullToReduced N Γ) := by
  intro y
  refine Quotient.inductionOn' y ?_
  intro k
  refine Quotient.inductionOn' k ?_
  intro g
  exact ⟨QuotientGroup.mk g, fullToReduced_mk N Γ g⟩

/-- Compactness descends from the unreduced homogeneous space along the
canonical continuous surjection. -/
noncomputable def reducedQuotientCompactSpace
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H)
    [CompactSpace (Quotient N Γ)] :
    CompactSpace (ReducedQuotient N Γ) where
  isCompact_univ := by
    have hcompact :=
      isCompact_univ.image (continuous_fullToReduced N Γ)
    rw [Set.image_univ,
      Set.range_eq_univ.mpr (surjective_fullToReduced N Γ)] at hcompact
    exact hcompact

/-- The progression generator after passing to the reduced group. -/
def reducedProgressionGenerator
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    ReducedGroup N :=
  QuotientGroup.mk' (averagingNormalSubgroup N)
    (progressionGenerator N)

/-- Translation by the reduced progression generator on the real reduced
Hall--Petresco quotient. -/
def reducedStep
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) :
    ReducedQuotient N Γ → ReducedQuotient N Γ :=
  fun q ↦ reducedProgressionGenerator N • q

theorem continuous_reducedStep
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) :
    Continuous (reducedStep N Γ) := by
  exact continuous_const_smul _

/-- The canonical quotient map is a factor map for the progression
translations. -/
theorem fullToReduced_quotientStep
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (q : Quotient N Γ) :
    fullToReduced N Γ (quotientStep N Γ q) =
      reducedStep N Γ (fullToReduced N Γ q) := by
  refine Quotient.inductionOn' q ?_
  intro g
  simp [quotientStep, reducedStep, reducedProgressionGenerator,
    fullToReduced_mk]

theorem fullToReduced_quotientStep_iterate
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (n : ℕ) (q : Quotient N Γ) :
    fullToReduced N Γ (((quotientStep N Γ)^[n]) q) =
      ((reducedStep N Γ)^[n]) (fullToReduced N Γ q) := by
  exact
    (Function.Semiconj.iterate_right
      (fullToReduced_quotientStep N Γ) n) q

end Chapter02.HallPetrescoReducedQuotient
