import Chapter02.HallPetresco.HallPetrescoCentralExtensionMinimality
import Chapter02.HallPetresco.NilsystemPropertyHReduction

open Classical Set
open scoped Pointwise

noncomputable section

namespace Chapter02.HallPetrescoParryPropertyH

open Chapter02.HallPetrescoReducedQuotient
open Chapter02.HallPetrescoReducedAbelianFactor
open Chapter02.HallPetrescoTwoStepGroup
open Chapter02.HallPetrescoNormalForm
open Chapter02.HallPetrescoCentralExtensionMinimality
open Chapter02.HallPetrescoMeasureOrbit
open Chapter02.NilsystemPropertyHReduction
open Chapter02.HostKraStructuredRecurrence

universe u v

/-- For a continuous action of a topological group, the setwise stabilizer
of a closed subset is closed.  The inverse condition is included explicitly
so that equality of the translated set is expressed by closed pointwise
conditions. -/
theorem isClosed_setwiseStabilizer
    {G : Type u} {Y : Type v}
    [Group G] [TopologicalSpace G] [IsTopologicalGroup G]
    [TopologicalSpace Y] [MulAction G Y] [ContinuousSMul G Y]
    (C : Set Y) (hC : IsClosed C) :
    IsClosed (MulAction.stabilizer G C : Set G) := by
  have hcarrier :
      (MulAction.stabilizer G C : Set G) =
        (⋂ y ∈ C, {g : G | g • y ∈ C}) ∩
          (⋂ y ∈ C, {g : G | g⁻¹ • y ∈ C}) := by
    ext g
    constructor
    · intro hg
      change g ∈ MulAction.stabilizer G C at hg
      have hginv :
          g⁻¹ ∈ MulAction.stabilizer G C :=
        (MulAction.stabilizer G C).inv_mem hg
      rw [MulAction.mem_stabilizer_iff] at hg hginv
      constructor
      · simp only [mem_iInter]
        intro y hy
        rw [← hg]
        exact ⟨y, hy, rfl⟩
      · simp only [mem_iInter]
        intro y hy
        rw [← hginv]
        exact ⟨y, hy, rfl⟩
    · rintro ⟨hforward, hinverse⟩
      change g ∈ MulAction.stabilizer G C
      rw [MulAction.mem_stabilizer_iff]
      apply Set.Subset.antisymm
      · rintro y ⟨x, hx, rfl⟩
        exact (mem_iInter.mp (mem_iInter.mp hforward x) hx)
      · intro y hy
        refine ⟨g⁻¹ • y,
          mem_iInter.mp (mem_iInter.mp hinverse y) hy, ?_⟩
        simp
  rw [hcarrier]
  apply IsClosed.inter
  · exact isClosed_biInter fun y _ ↦
      hC.preimage (continuous_id.smul continuous_const)
  · exact isClosed_biInter fun y _ ↦
      hC.preimage (continuous_inv.smul continuous_const)

/-- The complete commutator subgroup of the reduced Hall--Petresco group
lies in its identity component.  This is the exact connected-commutator
input in the two-step Parry criterion. -/
theorem reduced_commutator_le_connectedComponentOfOne
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    _root_.commutator (ReducedGroup N) ≤
      Subgroup.connectedComponentOfOne (ReducedGroup N) := by
  intro h hh
  exact
    (isConnected_commutator_reducedGroup N).subset_connectedComponent
      (show (1 : ReducedGroup N) ∈
          (_root_.commutator (ReducedGroup N) :
            Set (ReducedGroup N)) by
        exact (_root_.commutator (ReducedGroup N)).one_mem)
      hh

/-- The property-(H) subgroup of the reduced Hall--Petresco group,
generated by its identity component and the progression element. -/
def reducedIdentityTranslationSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    Subgroup (ReducedGroup N) :=
  identityTranslationSubgroup
    (ReducedGroup N) (reducedProgressionGenerator N)

theorem reduced_progression_mem_identityTranslationSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    reducedProgressionGenerator N ∈
      reducedIdentityTranslationSubgroup N :=
  translation_mem_identityTranslationSubgroup
    (ReducedGroup N) (reducedProgressionGenerator N)

/-- In particular the reduced property-(H) subgroup already contains the
whole vertical quadratic torus, since that torus is the full commutator
subgroup. -/
theorem reduced_commutator_le_identityTranslationSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    _root_.commutator (ReducedGroup N) ≤
      reducedIdentityTranslationSubgroup N :=
  (reduced_commutator_le_connectedComponentOfOne N).trans
    (connectedComponentOfOne_le_identityTranslationSubgroup
      (ReducedGroup N) (reducedProgressionGenerator N))

/-- The pure linear Hall coefficient depends continuously on the original
group element after passage to the reduced Hall--Petresco group. -/
theorem continuous_linearReducedElement
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    Continuous (linearReducedElement N) := by
  apply QuotientGroup.continuous_mk.comp
  apply Continuous.subtype_mk
  rw [continuous_pi_iff]
  intro j
  exact continuous_id.pow j.val

/-- Linear Hall elements coming from the original identity component lie
in the identity component of the reduced Hall--Petresco group. -/
theorem linearReducedElement_mem_connectedComponentOfOne
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (h : H) (hh : h ∈ Subgroup.connectedComponentOfOne H) :
    linearReducedElement N h ∈
      Subgroup.connectedComponentOfOne (ReducedGroup N) := by
  let C := Subgroup.connectedComponentOfOne H
  letI : ConnectedSpace C := by
    change ConnectedSpace (connectedComponent (1 : H))
    exact isConnected_iff_connectedSpace.mp
      (isConnected_connectedComponent (x := (1 : H)))
  let f : C → ReducedGroup N := fun g ↦ linearReducedElement N g
  have hf : Continuous f :=
    (continuous_linearReducedElement N).comp continuous_subtype_val
  apply (isConnected_range hf).subset_connectedComponent
  · refine ⟨1, ?_⟩
    change linearReducedElement N 1 = 1
    apply congrArg (QuotientGroup.mk' (averagingNormalSubgroup N))
    apply Subtype.ext
    funext j
    simp [linear]
  · exact ⟨⟨h, hh⟩, rfl⟩

@[simp]
theorem reducedLinearAbelianHom_linearReducedElement
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) (h : H) :
    reducedLinearAbelianHom N (linearReducedElement N h) =
      Abelianization.of h := by
  change Abelianization.of (extractedLinear (linear h)) =
    Abelianization.of h
  rw [linear_eq_hallTuple N h, extractedLinear_hallTuple]

/-- Property (H) passes from the original nilpotent group to the actual
reduced Hall--Petresco group.  The proof uses the common abelian factor:
the connected linear directions and the progression generator cover that
factor, while the entire quadratic kernel is already connected. -/
theorem reducedIdentityTranslationSubgroup_eq_top_of_propertyH
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (hproperty :
      identityTranslationSubgroup H N.translation = ⊤) :
    reducedIdentityTranslationSubgroup N = ⊤ := by
  let R := ReducedGroup N
  let L : Subgroup R := reducedIdentityTranslationSubgroup N
  let φ : R →* AbelianFactor H := reducedLinearAbelianHom N
  let S : Subgroup H := (L.map φ).comap Abelianization.of
  have hgenerated : identityTranslationSubgroup H N.translation ≤ S := by
    rw [identityTranslationSubgroup, Subgroup.closure_le]
    intro h hh
    rcases hh with hh | rfl
    · change Abelianization.of h ∈ L.map φ
      let l : R := linearReducedElement N h
      have hl0 :
          l ∈ Subgroup.connectedComponentOfOne R :=
        linearReducedElement_mem_connectedComponentOfOne N h hh
      have hlL : l ∈ L :=
        connectedComponentOfOne_le_identityTranslationSubgroup
          R (reducedProgressionGenerator N) hl0
      exact ⟨l, hlL, reducedLinearAbelianHom_linearReducedElement N h⟩
    · change Abelianization.of N.translation ∈ L.map φ
      let l : R := reducedProgressionGenerator N
      have hlL : l ∈ L :=
        reduced_progression_mem_identityTranslationSubgroup N
      refine ⟨l, hlL, ?_⟩
      exact reducedLinearAbelianHom_progression N
  have hStop : S = ⊤ := by
    apply top_unique
    have htop : (⊤ : Subgroup H) ≤ S := by
      simpa [hproperty] using hgenerated
    exact htop
  apply top_unique
  intro k _
  obtain ⟨h, hh⟩ :
      ∃ h : H, Abelianization.of h = φ k :=
    QuotientGroup.mk_surjective (φ k)
  have hhS : h ∈ S := by
    rw [hStop]
    exact Subgroup.mem_top h
  change Abelianization.of h ∈ L.map φ at hhS
  obtain ⟨l, hlL, hφl⟩ := hhS
  have hker : k * l⁻¹ ∈ φ.ker := by
    change φ (k * l⁻¹) = 1
    rw [map_mul, map_inv, hφl, hh]
    simp
  have hcomm :
      k * l⁻¹ ∈ _root_.commutator R := by
    rw [← ker_reducedLinearAbelianHom_eq_commutator N]
    exact hker
  have hdiffL : k * l⁻¹ ∈ L :=
    reduced_commutator_le_identityTranslationSubgroup N hcomm
  have hmul : (k * l⁻¹) * l ∈ L :=
    L.mul_mem hdiffL hlL
  have hkl : (k * l⁻¹) * l = k := by group
  rw [hkl] at hmul
  exact hmul

/-- The setwise stabilizer used in the reduced Parry argument is a genuine
closed subgroup of the reduced Hall--Petresco group. -/
theorem orbitClosureStabilizer_isClosed
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (q : ReducedQuotient N Γ) :
    IsClosed
      (orbitClosureStabilizer N Γ q : Set (ReducedGroup N)) :=
  isClosed_setwiseStabilizer
    (G := ReducedGroup N) (Y := ReducedQuotient N Γ)
    (closure (forwardOrbit (reducedStep N Γ) q)) isClosed_closure

/-- The part of the orbit-closure stabilizer lying in the identity
component.  This is the subgroup on which the connectedness argument in
Parry's criterion takes place. -/
def identityOrbitClosureStabilizer
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (q : ReducedQuotient N Γ) :
    Subgroup (Subgroup.connectedComponentOfOne (ReducedGroup N)) :=
  (orbitClosureStabilizer N Γ q).comap
    (Subgroup.connectedComponentOfOne (ReducedGroup N)).subtype

/-- The identity-component part of the orbit-closure stabilizer is closed.
Thus the remaining local Parry input is precisely that this subgroup is
also open. -/
theorem identityOrbitClosureStabilizer_isClosed
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (q : ReducedQuotient N Γ) :
    IsClosed
      (identityOrbitClosureStabilizer N Γ q :
        Set (Subgroup.connectedComponentOfOne (ReducedGroup N))) := by
  exact (orbitClosureStabilizer_isClosed N Γ q).preimage
    continuous_subtype_val

/-- An open subgroup of the identity component is the whole identity
component.  Applied here, local openness of the orbit-closure stabilizer
is enough for the full identity-component stabilization required by
Parry's criterion. -/
theorem connectedComponentOfOne_le_orbitClosureStabilizer_of_isOpen
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (q : ReducedQuotient N Γ)
    (hopen : IsOpen
      (identityOrbitClosureStabilizer N Γ q :
        Set (Subgroup.connectedComponentOfOne (ReducedGroup N)))) :
    Subgroup.connectedComponentOfOne (ReducedGroup N) ≤
      orbitClosureStabilizer N Γ q := by
  let C := Subgroup.connectedComponentOfOne (ReducedGroup N)
  let K : Subgroup C := identityOrbitClosureStabilizer N Γ q
  letI : ConnectedSpace C := by
    change ConnectedSpace
      (connectedComponent (1 : ReducedGroup N))
    exact isConnected_iff_connectedSpace.mp
      (isConnected_connectedComponent (x := (1 : ReducedGroup N)))
  have hKclopen : IsClopen (K : Set C) :=
    ⟨K.isClosed_of_isOpen hopen, hopen⟩
  have hKuniv : (K : Set C) = Set.univ :=
    hKclopen.eq_univ ⟨1, K.one_mem⟩
  intro g hg
  have hsub : (⟨g, hg⟩ : C) ∈ K := by
    change (⟨g, hg⟩ : C) ∈ (K : Set C)
    rw [hKuniv]
    exact Set.mem_univ _
  exact hsub

/-- A pointwise Parry statement only for the identity component is enough
to close the previously isolated vertical-return obligation. -/
theorem hasFullQuadraticFiberOrbitClosure_of_connectedComponent_le_stabilizer
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H)
    (hidentity : ∀ q : ReducedQuotient N Γ,
      Subgroup.connectedComponentOfOne (ReducedGroup N) ≤
        orbitClosureStabilizer N Γ q) :
    HasFullQuadraticFiberOrbitClosure N Γ := by
  apply hasFullQuadraticFiberOrbitClosure_of_commutator_le_stabilizer
  intro q
  exact (reduced_commutator_le_connectedComponentOfOne N).trans
    (hidentity q)

/-- The reduced Hall--Petresco vertical-fiber conclusion follows from the
single local statement that every orbit-closure stabilizer is open inside
the identity component. -/
theorem hasFullQuadraticFiberOrbitClosure_of_identityStabilizer_isOpen
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H)
    (hopen : ∀ q : ReducedQuotient N Γ, IsOpen
      (identityOrbitClosureStabilizer N Γ q :
        Set (Subgroup.connectedComponentOfOne (ReducedGroup N)))) :
    HasFullQuadraticFiberOrbitClosure N Γ :=
  hasFullQuadraticFiberOrbitClosure_of_connectedComponent_le_stabilizer
    N Γ fun q ↦
      connectedComponentOfOne_le_orbitClosureStabilizer_of_isOpen
        N Γ q (hopen q)

/-- Hence identity-component stability directly supplies minimality of the
actual reduced Hall--Petresco progression whenever the genuine quotient
presentation is available. -/
theorem everyOrbitHitsOpen_reducedStep_of_connectedComponent_le_stabilizer
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [MetricSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (P : Chapter02.ToralTwoStepNilsystem.QuotientPresentation N)
    (hidentity : ∀ q : ReducedQuotient N P.lattice,
      Subgroup.connectedComponentOfOne (ReducedGroup N) ≤
        orbitClosureStabilizer N P.lattice q) :
    Chapter02.HostKraStructuredRecurrence.EveryOrbitHitsOpen
      (reducedStep N P.lattice) :=
  everyOrbitHitsOpen_reducedStep_of_fullQuadraticFiber
    N P
    (hasFullQuadraticFiberOrbitClosure_of_connectedComponent_le_stabilizer
      N P.lattice hidentity)

/-- The same local openness condition therefore implies minimality of the
actual reduced Hall--Petresco progression on the genuine quotient. -/
theorem everyOrbitHitsOpen_reducedStep_of_identityStabilizer_isOpen
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [MetricSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (P : Chapter02.ToralTwoStepNilsystem.QuotientPresentation N)
    (hopen : ∀ q : ReducedQuotient N P.lattice, IsOpen
      (identityOrbitClosureStabilizer N P.lattice q :
        Set (Subgroup.connectedComponentOfOne (ReducedGroup N)))) :
    Chapter02.HostKraStructuredRecurrence.EveryOrbitHitsOpen
      (reducedStep N P.lattice) :=
  everyOrbitHitsOpen_reducedStep_of_connectedComponent_le_stabilizer
    N P fun q ↦
      connectedComponentOfOne_le_orbitClosureStabilizer_of_isOpen
        N P.lattice q (hopen q)

end Chapter02.HallPetrescoParryPropertyH
