import Chapter02.HallPetresco.HallPetrescoStabilizerPairwiseCommutator
import Chapter02.HallPetresco.HallPetrescoAveragedMinimalPresentation

open Classical Set

noncomputable section

namespace Chapter02.HallPetrescoStabilizerGeneratedCommutator

open Chapter02.HallPetrescoCentralExtensionMinimality
open Chapter02.HallPetrescoReducedQuotient
open Chapter02.HallPetrescoAveragedMinimalPresentation
open Chapter02.HallPetrescoStabilizerPairwiseCommutator
open Chapter02.HallPetrescoVerticalCharacter

universe u v

/-- The algebraic subgroup generated by all quadratic parameters of
pairwise commutators in one progression orbit-closure stabilizer. -/
def generatedPairwiseStabilizerCommutatorSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (q : ReducedQuotient N Γ) :
    Subgroup (Fin N.torusDim → Circle) :=
  Subgroup.closure
    (pairwiseStabilizerCommutatorParameters N Γ q)

/-- The generated-commutator form of the remaining Parry condition:
the algebraic subgroup generated by pairwise stabilizer commutators is
dense in the full vertical torus.  This is strictly weaker than density
of the set of single commutator parameters. -/
def HasDenseGeneratedPairwiseStabilizerCommutators
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) : Prop :=
  ∀ q : ReducedQuotient N Γ,
    Dense
      (generatedPairwiseStabilizerCommutatorSubgroup N Γ q :
        Set (Fin N.torusDim → Circle))

/-- A return-annihilating vertical character is one on the entire closed
subgroup generated by pairwise stabilizer commutator parameters. -/
theorem verticalCharacter_eq_one_on_generatedPairwiseCommutators
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H) (q : ReducedQuotient N Γ)
    (χ : Chapter02.ContinuousMultiplicativeCircleCharacter
      (Fin N.torusDim → Circle))
    (hχreturn :
      ∀ z ∈ quadraticReturnSubgroup N Γ q, χ.toFun z = 1) :
    ∀ z ∈ generatedPairwiseStabilizerCommutatorSubgroup N Γ q,
      χ.toFun z = 1 := by
  intro z hz
  change z ∈ Subgroup.closure
      (pairwiseStabilizerCommutatorParameters N Γ q) at hz
  induction hz using Subgroup.closure_induction with
  | mem z hz =>
      rcases hz with ⟨g, h, hg, hh, hcomm⟩
      exact
        verticalCharacter_commutator_eq_one_of_mem_stabilizers
          N Γ q χ hχreturn g h hg hh z hcomm
  | one =>
      exact χ.map_one
  | mul a b _ _ ha hb =>
      rw [χ.map_mul, ha, hb, one_mul]
  | inv a _ ha =>
      have hmul := χ.map_mul a a⁻¹
      rw [mul_inv_cancel, χ.map_one, ha, one_mul] at hmul
      exact hmul.symm

/-- Full generation by pairwise stabilizer commutators rules out every
proper quadratic return subgroup and hence supplies the full vertical
Hall--Petresco recurrence. -/
theorem hasFullQuadraticFiberOrbitClosure_of_denseGeneratedPairwiseCommutators
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [MetricSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (P : Chapter02.ToralTwoStepNilsystem.QuotientPresentation N)
    (hgenerated :
      HasDenseGeneratedPairwiseStabilizerCommutators N P.lattice) :
    HasFullQuadraticFiberOrbitClosure N P.lattice := by
  rw [hasFullQuadraticFiberOrbitClosure_iff_returnSubgroup_eq_top]
  intro q
  by_contra hne
  obtain ⟨χ, hχreturn, z, hχz⟩ :=
    exists_verticalCharacter_of_quadraticReturnSubgroup_ne_top
      N P.lattice q hne
  let K : Set (Fin N.torusDim → Circle) :=
    generatedPairwiseStabilizerCommutatorSubgroup
      N P.lattice q
  let E : Set (Fin N.torusDim → Circle) :=
    {w | χ.toFun w = 1}
  have hKE : K ⊆ E := by
    intro w hw
    exact
      verticalCharacter_eq_one_on_generatedPairwiseCommutators
        N P.lattice q χ hχreturn w hw
  have hEclosed : IsClosed E :=
    isClosed_eq χ.continuous continuous_const
  have hclosure : closure K ⊆ E :=
    closure_minimal hKE hEclosed
  have hKdense : Dense K := hgenerated q
  rw [hKdense.closure_eq] at hclosure
  exact hχz (hclosure (Set.mem_univ z))

/-- The weaker generated-commutator density condition therefore gives the
actual compact-minimal Hall--Petresco correlation orbit for every
continuous observation on a toral two-step model. -/
theorem exists_correlationOrbit_of_denseGeneratedPairwiseCommutators
    {H : Type} {X : Type}
    [Group H] [MetricSpace H] [IsTopologicalGroup H]
    [LocallyCompactSpace H]
    [MetricSpace X] [CompactSpace X]
    [MeasurableSpace X] [BorelSpace X] {μ : MeasureTheory.Measure X}
    [MeasureTheory.IsProbabilityMeasure μ]
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (P : Chapter02.ToralTwoStepNilsystem.QuotientPresentation N)
    [MeasurableSpace
      (Chapter02.HallPetrescoLattice.Quotient N P.lattice)]
    [BorelSpace
      (Chapter02.HallPetrescoLattice.Quotient N P.lattice)]
    (m : MeasureTheory.Measure (Fin N.torusDim → Circle))
    [MeasureTheory.IsProbabilityMeasure m]
    [m.IsMulLeftInvariant]
    (hgenerated :
      HasDenseGeneratedPairwiseStabilizerCommutators N P.lattice)
    (f : C(X, ℝ)) :
    ∃ ν : MeasureTheory.ProbabilityMeasure
        (Chapter02.HallPetrescoTwoStepGroup.Vertex → X),
      Chapter02.HostKraHallPetrescoCorrelation.HasHallPetrescoCorrelationOrbit
        m μ (Chapter02.toCompactCentralAction N.centralAction) f
        (Chapter02.HallPetrescoMeasureOrbit.measureOrbitCorrelation
          N ν f) := by
  exact
    exists_correlationOrbit_of_fullQuadraticFiber N P m
      (hasFullQuadraticFiberOrbitClosure_of_denseGeneratedPairwiseCommutators
        N P hgenerated)
      f

/-- The earlier density condition on the set of single pairwise
commutator parameters implies density of the subgroup they generate. -/
theorem denseGeneratedPairwiseCommutators_of_densePairwiseCommutators
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (Γ : Subgroup H)
    (hdense :
      HasDensePairwiseStabilizerCommutatorParameters N Γ) :
    HasDenseGeneratedPairwiseStabilizerCommutators N Γ := by
  intro q
  apply (hdense q).mono
  intro z hz
  exact Subgroup.subset_closure hz

end Chapter02.HallPetrescoStabilizerGeneratedCommutator
