import Chapter02.HallPetresco.ToralTwoStepNilsystem

open Classical

noncomputable section

namespace Chapter02.HallPetrescoTwoStepGroup

universe u v

/-- The four coordinates used for a progression of length four. -/
abbrev Vertex := Fin 4

/-- The diagonal copy of a group element in four coordinates. -/
def diagonal {H : Type u} [Group H] (g : H) : Vertex → H :=
  fun _ ↦ g

/-- The linear Hall--Petresco generator
`(1,g,g²,g³)`. -/
def linear {H : Type u} [Group H] (g : H) : Vertex → H :=
  fun j ↦ g ^ j.val

/-- The quadratic central generator
`(1,1,z,z³)`, whose exponents are the binomial coefficients
`choose(j,2)`. -/
def quadratic {H : Type u} [Group H] (z : H) : Vertex → H :=
  fun j ↦ z ^ j.val.choose 2

/-- The `n`-th arithmetic-progression tuple
`(1,aⁿ,a²ⁿ,a³ⁿ)`. -/
def arithmeticProgression {H : Type u} [Group H]
    (a : H) (n : ℕ) : Vertex → H :=
  fun j ↦ a ^ (j.val * n)

@[simp]
theorem diagonal_apply {H : Type u} [Group H]
    (g : H) (j : Vertex) :
    diagonal g j = g :=
  rfl

@[simp]
theorem linear_apply {H : Type u} [Group H]
    (g : H) (j : Vertex) :
    linear g j = g ^ j.val :=
  rfl

@[simp]
theorem quadratic_apply {H : Type u} [Group H]
    (z : H) (j : Vertex) :
    quadratic z j = z ^ j.val.choose 2 :=
  rfl

@[simp]
theorem arithmeticProgression_apply
    {H : Type u} [Group H] (a : H) (n : ℕ) (j : Vertex) :
    arithmeticProgression a n j = a ^ (j.val * n) :=
  rfl

theorem arithmeticProgression_eq_linear_pow
    {H : Type u} [Group H] (a : H) (n : ℕ) :
    arithmeticProgression a n = linear a ^ n := by
  funext j
  change a ^ (j.val * n) = (a ^ j.val) ^ n
  exact pow_mul a j.val n

@[simp]
theorem arithmeticProgression_zero
    {H : Type u} [Group H] (a : H) :
    arithmeticProgression a 0 = 1 := by
  rw [arithmeticProgression_eq_linear_pow, pow_zero]

theorem arithmeticProgression_add
    {H : Type u} [Group H] (a : H) (m n : ℕ) :
    arithmeticProgression a (m + n) =
      arithmeticProgression a m * arithmeticProgression a n := by
  rw [arithmeticProgression_eq_linear_pow,
    arithmeticProgression_eq_linear_pow,
    arithmeticProgression_eq_linear_pow, pow_add]

/-- The algebraic subgroup generated by diagonal translations, linear
progression directions, and the chosen central torus in the quadratic
direction. -/
def algebraicSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    Subgroup (Vertex → H) :=
  Subgroup.closure
    (Set.range (diagonal : H → Vertex → H) ∪
      Set.range (linear : H → Vertex → H) ∪
      Set.range (fun z : Fin N.torusDim → Circle ↦
        quadratic (N.centralHom z)))

/-- The concrete closed two-step Hall--Petresco subgroup.  BHK's
`G̃` is the topological closure of the algebraically generated polynomial
progression group. -/
def subgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    Subgroup (Vertex → H) :=
  (algebraicSubgroup N).topologicalClosure

instance subgroup_isClosed
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    IsClosed (subgroup N : Set (Vertex → H)) :=
  Subgroup.isClosed_topologicalClosure _

theorem diagonal_mem_subgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) (g : H) :
    diagonal g ∈ subgroup N := by
  apply Subgroup.le_topologicalClosure
  apply Subgroup.subset_closure
  exact Or.inl (Or.inl ⟨g, rfl⟩)

theorem linear_mem_subgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) (g : H) :
    linear g ∈ subgroup N := by
  apply Subgroup.le_topologicalClosure
  apply Subgroup.subset_closure
  exact Or.inl (Or.inr ⟨g, rfl⟩)

theorem quadratic_central_mem_subgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (z : Fin N.torusDim → Circle) :
    quadratic (N.centralHom z) ∈ subgroup N := by
  apply Subgroup.le_topologicalClosure
  apply Subgroup.subset_closure
  exact Or.inr ⟨z, rfl⟩

/-- Every time-`n` progression tuple lies in the Hall--Petresco subgroup. -/
theorem arithmeticProgression_mem_subgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) (n : ℕ) :
    arithmeticProgression N.translation n ∈ subgroup N := by
  rw [arithmeticProgression_eq_linear_pow]
  exact (subgroup N).pow_mem (linear_mem_subgroup N N.translation) n

/-- The four points obtained by letting the arithmetic-progression group
tuple act on a diagonal base point. -/
def orbitConfiguration
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (x : X) (n : ℕ) : Vertex → X :=
  fun j ↦ N.ambientAction.toMulAction.smul
    (arithmeticProgression N.translation n j) x

/-- Each coordinate of the Hall--Petresco configuration is exactly the
corresponding multiple iterate of the nilrotation. -/
theorem orbitConfiguration_apply
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (x : X) (n : ℕ) (j : Vertex) :
    orbitConfiguration N x n j =
      (N.nilrotation^[j.val * n]) x := by
  rw [N.nilrotation_iterate]
  rfl

/-- Product observation on the four Hall--Petresco coordinates. -/
def fourfoldObservation
    {X : Type v} (f : X → ℝ) (y : Vertex → X) : ℝ :=
  ∏ j, f (y j)

theorem fourfoldObservation_orbitConfiguration
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (f : X → ℝ) (x : X) (n : ℕ) :
    fourfoldObservation f (orbitConfiguration N x n) =
      f x * f ((N.nilrotation^[n]) x) *
        f ((N.nilrotation^[2 * n]) x) *
          f ((N.nilrotation^[3 * n]) x) := by
  simp only [fourfoldObservation, orbitConfiguration_apply]
  simp [Fin.prod_univ_succ]
  ring

end Chapter02.HallPetrescoTwoStepGroup
