import Chapter02.HallPetresco.ToralTwoStepNilsystem
import Mathlib.Topology.Algebra.OpenSubgroup
import Mathlib.Topology.Connected.LocallyConnected

open Classical Set

noncomputable section

namespace Chapter02.NilsystemPropertyHReduction

open Chapter02.HostKraStructuredRecurrence

universe u v

/-- The subgroup generated by the identity component and one translating
element.  This is the exact subgroup used in the BHK property-(H)
replacement. -/
def identityTranslationSubgroup
    (H : Type u) [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (a : H) : Subgroup H :=
  Subgroup.closure
    ((Subgroup.connectedComponentOfOne H : Set H) ∪ {a})

theorem connectedComponentOfOne_le_identityTranslationSubgroup
    (H : Type u) [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (a : H) :
    Subgroup.connectedComponentOfOne H ≤
      identityTranslationSubgroup H a := by
  intro h hh
  apply Subgroup.subset_closure
  exact Or.inl hh

theorem translation_mem_identityTranslationSubgroup
    (H : Type u) [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (a : H) :
    a ∈ identityTranslationSubgroup H a := by
  apply Subgroup.subset_closure
  exact Or.inr (Set.mem_singleton a)

/-- In a locally connected group the BHK property-(H) subgroup is open,
because it contains the open identity component. -/
theorem isOpen_identityTranslationSubgroup
    (H : Type u) [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [LocallyConnectedSpace H] (a : H) :
    IsOpen (identityTranslationSubgroup H a : Set H) := by
  apply Subgroup.isOpen_mono
    (connectedComponentOfOne_le_identityTranslationSubgroup H a)
  exact isOpen_connectedComponent

/-- The ambient identity component remains inside the identity component
after corestriction to the property-(H) subgroup.  The reverse inclusion
follows from continuity of the subtype map, but this direction is the one
needed to prove that the replacement group satisfies property (H)
internally. -/
theorem connectedComponentOfOne_mem_replacementConnectedComponent
    (H : Type u) [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (a h : H) (hh : h ∈ Subgroup.connectedComponentOfOne H) :
    (⟨h, connectedComponentOfOne_le_identityTranslationSubgroup H a hh⟩ :
        identityTranslationSubgroup H a) ∈
      Subgroup.connectedComponentOfOne
        (identityTranslationSubgroup H a) := by
  let C := Subgroup.connectedComponentOfOne H
  let K := identityTranslationSubgroup H a
  letI : ConnectedSpace C := by
    change ConnectedSpace (connectedComponent (1 : H))
    exact isConnected_iff_connectedSpace.mp
      (isConnected_connectedComponent (x := (1 : H)))
  let f : C → K := fun x ↦
    ⟨x, connectedComponentOfOne_le_identityTranslationSubgroup
      H a x.property⟩
  have hf : Continuous f :=
    continuous_subtype_val.subtype_mk _
  apply (isConnected_range hf).subset_connectedComponent
  · refine ⟨1, ?_⟩
    apply Subtype.ext
    rfl
  · refine ⟨⟨h, hh⟩, ?_⟩
    rfl

/-- The distinguished compact commutator torus lies in the identity
component of the ambient group.  This is a consequence of the actual
continuous torus parameterization, not an additional connectedness
assumption on the commutator subgroup. -/
theorem centralHom_mem_connectedComponentOfOne
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (z : Fin N.torusDim → Circle) :
    N.centralHom z ∈ Subgroup.connectedComponentOfOne H := by
  letI : PathConnectedSpace (AddCircle (1 : ℝ)) :=
    AddCircle.pathConnectedSpace 1
  letI : ConnectedSpace Circle :=
    (AddCircle.homeomorphCircle one_ne_zero).surjective.connectedSpace
      (AddCircle.homeomorphCircle one_ne_zero).continuous
  letI : ∀ _ : Fin N.torusDim, ConnectedSpace Circle :=
    fun _ ↦ inferInstance
  have hconnected : IsConnected (Set.range N.centralHom) := by
    simpa only [Set.image_univ] using
      isConnected_univ.image N.centralHom
        N.continuous_centralHom.continuousOn
  apply hconnected.subset_connectedComponent
  · exact ⟨1, map_one N.centralHom⟩
  · exact ⟨z, rfl⟩

/-- Consequently the full ambient commutator subgroup is already contained
in the BHK property-(H) replacement subgroup. -/
theorem commutator_le_identityTranslationSubgroup
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    _root_.commutator H ≤
      identityTranslationSubgroup H N.translation := by
  rw [← N.centralHom_range]
  rintro h ⟨z, rfl⟩
  exact connectedComponentOfOne_le_identityTranslationSubgroup
    H N.translation (centralHom_mem_connectedComponentOfOne N z)

/-- Every orbit map of a genuinely presented homogeneous action is open. -/
theorem isOpenMap_ambientOrbitMap
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (P : Chapter02.ToralTwoStepNilsystem.QuotientPresentation N)
    (x : X) :
    IsOpenMap (fun h : H ↦
      N.ambientAction.toMulAction.smul h x) := by
  obtain ⟨g, hg⟩ :
      ∃ g : H, (QuotientGroup.mk g : H ⧸ P.lattice) =
        P.toQuotient x :=
    QuotientGroup.mk_surjective (P.toQuotient x)
  have hfun :
      (fun h : H ↦ N.ambientAction.toMulAction.smul h x) =
        P.toQuotient.symm ∘
          (fun h : H ↦ (QuotientGroup.mk (h * g) :
            H ⧸ P.lattice)) := by
    funext h
    apply P.toQuotient.injective
    rw [P.equivariant]
    change h • P.toQuotient x =
      P.toQuotient
        (P.toQuotient.symm
          (QuotientGroup.mk (h * g) : H ⧸ P.lattice))
    rw [Homeomorph.apply_symm_apply, ← hg]
    rfl
  rw [hfun]
  apply P.toQuotient.symm.isOpenMap.comp
  exact QuotientGroup.isOpenMap_coe.comp
    (Homeomorph.mulRight g).isOpenMap

/-- Orbit of a point under the property-(H) replacement subgroup. -/
def identityTranslationOrbit
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (x : X) : Set X :=
  {y | ∃ k : identityTranslationSubgroup H N.translation,
    N.ambientAction.toMulAction.smul (k : H) x = y}

theorem isOpen_identityTranslationOrbit
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [LocallyConnectedSpace H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (P : Chapter02.ToralTwoStepNilsystem.QuotientPresentation N)
    (x : X) :
    IsOpen (identityTranslationOrbit N x) := by
  have himage :
      identityTranslationOrbit N x =
        (fun h : H ↦ N.ambientAction.toMulAction.smul h x) ''
          (identityTranslationSubgroup H N.translation : Set H) := by
    ext y
    constructor
    · rintro ⟨k, rfl⟩
      exact ⟨k, k.property, rfl⟩
    · rintro ⟨h, hh, rfl⟩
      exact ⟨⟨h, hh⟩, rfl⟩
  rw [himage]
  exact isOpenMap_ambientOrbitMap N P x _
    (isOpen_identityTranslationSubgroup H N.translation)

/-- The standard BHK reduction is internal at the level of the homogeneous
action: for a locally connected presentation, minimality of the original
translation implies that the subgroup generated by the identity component
and the translation is still transitive on the same compact space. -/
theorem identityTranslationOrbit_eq_univ
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [LocallyConnectedSpace H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (P : Chapter02.ToralTwoStepNilsystem.QuotientPresentation N)
    (x : X) :
    identityTranslationOrbit N x = Set.univ := by
  apply Set.eq_univ_of_forall
  intro y
  have hopen := isOpen_identityTranslationOrbit N P x
  have hnonempty : (identityTranslationOrbit N x).Nonempty := by
    refine ⟨x, ⟨1, ?_⟩⟩
    exact N.ambientAction.toMulAction.one_smul x
  obtain ⟨n, hn⟩ := N.minimal_translation y
    (identityTranslationOrbit N x) hopen hnonempty
  change (N.nilrotation^[n]) y ∈ identityTranslationOrbit N x at hn
  rw [N.nilrotation_iterate] at hn
  rcases hn with ⟨k, hk⟩
  let K := identityTranslationSubgroup H N.translation
  have ha : N.translation ∈ K :=
    translation_mem_identityTranslationSubgroup H N.translation
  have hpow : N.translation ^ n ∈ K := K.pow_mem ha n
  refine ⟨⟨(N.translation ^ n)⁻¹ * k, K.mul_mem (K.inv_mem hpow) k.property⟩,
    ?_⟩
  change N.ambientAction.toMulAction.smul
      ((N.translation ^ n)⁻¹ * (k : H)) x = y
  calc
    _ = N.ambientAction.toMulAction.smul (N.translation ^ n)⁻¹
          (N.ambientAction.toMulAction.smul (k : H) x) :=
      N.ambientAction.toMulAction.mul_smul _ _ _
    _ = N.ambientAction.toMulAction.smul (N.translation ^ n)⁻¹
          (N.ambientAction.toMulAction.smul (N.translation ^ n) y) := by
      rw [hk]
    _ = N.ambientAction.toMulAction.smul
          ((N.translation ^ n)⁻¹ * N.translation ^ n) y := by
      exact (N.ambientAction.toMulAction.mul_smul _ _ _).symm
    _ = y := by
      rw [show (N.translation ^ n)⁻¹ * N.translation ^ n = 1 by group]
      exact N.ambientAction.toMulAction.one_smul y

/-- The ambient action restricted to the actual property-(H) replacement
subgroup. -/
def propertyHAction
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    Chapter02.LawfulCompactCentralAction
      (identityTranslationSubgroup H N.translation) X μ :=
  N.ambientAction.restrict
    (identityTranslationSubgroup H N.translation).subtype
    continuous_subtype_val

/-- The translating element as an element of the property-(H) group. -/
def propertyHTranslation
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    identityTranslationSubgroup H N.translation :=
  ⟨N.translation,
    translation_mem_identityTranslationSubgroup H N.translation⟩

/-- The replacement group really has BHK property (H) in its own
topology: it is generated by its own identity component together with the
distinguished translation.  This is proved from the construction, not
stored as an additional model hypothesis. -/
theorem identityTranslationSubgroup_has_propertyH
    (H : Type u) [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    (a : H) :
    identityTranslationSubgroup
        (identityTranslationSubgroup H a)
        (⟨a, translation_mem_identityTranslationSubgroup H a⟩ :
          identityTranslationSubgroup H a) =
      ⊤ := by
  let K := identityTranslationSubgroup H a
  let b : K :=
    ⟨a, translation_mem_identityTranslationSubgroup H a⟩
  let L := identityTranslationSubgroup K b
  apply top_unique
  intro k _
  have hKL : identityTranslationSubgroup H a ≤ L.map K.subtype := by
    rw [identityTranslationSubgroup, Subgroup.closure_le]
    intro h hh
    rcases hh with hh | rfl
    · let kh : K :=
        ⟨h, connectedComponentOfOne_le_identityTranslationSubgroup
          H a hh⟩
      have hkh :
          kh ∈ Subgroup.connectedComponentOfOne K := by
        exact
          connectedComponentOfOne_mem_replacementConnectedComponent
            H a h hh
      have hkhL : kh ∈ L :=
        connectedComponentOfOne_le_identityTranslationSubgroup K b hkh
      exact ⟨kh, hkhL, rfl⟩
    · have hbL : b ∈ L :=
        translation_mem_identityTranslationSubgroup K b
      exact ⟨b, hbL, rfl⟩
  obtain ⟨l, hl, hlk⟩ := hKL k.property
  have : l = k := by
    apply Subtype.ext
    exact hlk
  simpa [L, this] using hl

/-- The compact central torus homomorphism corestricted to the actual
property-(H) group. -/
def propertyHCentralHom
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    (Fin N.torusDim → Circle) →*
      identityTranslationSubgroup H N.translation :=
  N.centralHom.codRestrict
    (identityTranslationSubgroup H N.translation)
    (fun z ↦
      connectedComponentOfOne_le_identityTranslationSubgroup
        H N.translation
        (centralHom_mem_connectedComponentOfOne N z))

theorem continuous_propertyHCentralHom
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ) :
    Continuous (propertyHCentralHom N) := by
  exact N.continuous_centralHom.subtype_mk _

/-- The restricted action is still transitive on the same compact quotient.
This is the fully internal action-level content of the BHK replacement. -/
theorem transitive_propertyHAction
    {H : Type u} {X : Type v}
    [Group H] [TopologicalSpace H] [IsTopologicalGroup H]
    [LocallyConnectedSpace H]
    [TopologicalSpace X] [CompactSpace X]
    [MeasurableSpace X] {μ : MeasureTheory.Measure X}
    (N : Chapter02.ToralTwoStepNilsystem.Model H X μ)
    (P : Chapter02.ToralTwoStepNilsystem.QuotientPresentation N) :
    ∀ x y : X, ∃ k : identityTranslationSubgroup H N.translation,
      (propertyHAction N).toMulAction.smul k x = y := by
  intro x y
  have hy :
      y ∈ identityTranslationOrbit N x := by
    rw [identityTranslationOrbit_eq_univ N P x]
    exact Set.mem_univ y
  exact hy

end Chapter02.NilsystemPropertyHReduction
