import Chapter02.Section02

#check MeasureTheory.condExpL2
#check MeasureTheory.MemLp.condExpL2_ae_eq_condExp'
#check MeasureTheory.lpMeas
#check MeasureTheory.mem_lpMeas_iff
#check MeasureTheory.mem_lpMeas_iff_aestronglyMeasurable
#check MeasureTheory.lpMeas.coe_mem
#check MeasureTheory.Lp.compMeasurePreservingₗᵢ
#check LinearIsometry.toContinuousLinearMap
#check LinearIsometry.toContinuousLinearEquiv
#check MeasureTheory.Lp.coeFn_compMeasurePreserving
#check MeasureTheory.Lp.compMeasurePreserving_apply
#check MeasureTheory.Lp.compMeasurePreservingₗᵢ_apply
#check MeasureTheory.MemLp.toLp_sum
#check MeasureTheory.MemLp.toLp_const_smul
#check MeasureTheory.Lp.coeFn_finset_sum
#check MeasureTheory.AEStronglyMeasurable.mk
#check MeasureTheory.AEStronglyMeasurable.stronglyMeasurable_mk
#check MeasureTheory.AEStronglyMeasurable.ae_eq_mk
#check MeasureTheory.AEStronglyMeasurable.congr
#check MeasureTheory.Lp.integrable
#check MeasureTheory.MemLp.integrable
#check MeasureTheory.MemLp.mono_exponent
#check MeasureTheory.Lp.coeFn_sub
#check MeasureTheory.Lp.coeFn_smul
#check MeasureTheory.MeasurePreserving.iterate
#check MeasureTheory.MeasurePreserving.iterate_eq
#check MeasureTheory.MemLp.finset_sum
#check MeasureTheory.MemLp.sum
#check MeasureTheory.MemLp.const_smul
#check MeasureTheory.eLpNorm_toLp
#check ENNReal.ofReal_toReal
#check ENNReal.tendsto_ofReal
#check Filter.Tendsto.norm_sub
#check Submodule.eq_orthogonalProjection_of_eq_submodule
#check eq_orthogonalProjection_of_eq_submodule
#check Submodule.orthogonalProjection_eq_of_submodule_eq
#check MeasureTheory.condExpL2_eq
#check Submodule.orthogonalProjection_eq_iff
#check Submodule.orthogonalProjection_inner_eq_zero
#check Submodule.sub_orthogonalProjection_mem_orthogonal
#check Submodule.orthogonalProjection_mem_subspace_eq_self
#check Function.iterate_succ_apply'
#check Function.iterate_succ_apply
#check Function.iterate_succ
#check Function.iterate_succ'
#check MeasureTheory.Lp.coeFn_sum
#check MeasureTheory.Lp.coeFn_finset_sum
#check MeasureTheory.Lp.coeFn_add
#check Filter.EventuallyEq.finset_sum
#check Submodule.orthogonalProjection_eq_self_iff
